import {Nav,Footer} from "../components";import styles from "../legal.module.css";export const metadata={title:"Política de Privacidade"};
export default function Page(){return <><Nav/><main className={styles.page}><article className={styles.wrap}>
<span className={styles.eyebrow}>LGPD • PRIVACIDADE</span><h1>Política de Privacidade</h1><p className={styles.updated}>Versão vigente: 08 de setembro de 2026.</p>
<p>Esta Política explica como dados pessoais são tratados na ESTIBORDO, em observância à Lei nº 13.709/2018 (LGPD) e demais normas aplicáveis.</p>
<h2>1. Controlador</h2><p>O controlador é o fornecedor responsável pela ESTIBORDO: <strong>[NOME COMPLETO OU RAZÃO SOCIAL]</strong>, CPF/CNPJ <strong>[PREENCHER]</strong>, endereço <strong>[PREENCHER]</strong>. Canal de privacidade: estibordopscpp@gmail.com.</p>
<h2>2. Dados tratados</h2><ul><li>conta: e-mail, identificador de usuário e credencial armazenada de forma protegida;</li><li>perfil e contratação: nome, CPF, telefone e informações necessárias ao checkout;</li><li>aprendizagem: respostas, desempenho, progresso, revisões, metas, plano e tempo de estudo;</li><li>conteúdo fornecido pelo usuário: anotações, mapas e informações inseridas voluntariamente;</li><li>segurança e acesso: logs, eventos de autenticação, identificadores técnicos e representações derivadas de endereço IP quando utilizadas;</li><li>pagamento: identificadores, status, valor e referências da transação recebidas do provedor, sem armazenamento direto dos dados completos do cartão;</li><li>preferências e informações técnicas necessárias ao funcionamento do aplicativo.</li></ul>
<h2>3. Finalidades e bases legais</h2><p><strong>Execução de contrato e procedimentos preliminares:</strong> criar conta, autenticar, entregar recursos contratados, personalizar o plano de estudos, manter progresso, processar a contratação e prestar suporte.</p>
<p><strong>Cumprimento de obrigação legal ou regulatória:</strong> manter registros exigidos por normas fiscais, consumeristas, de internet ou outras aplicáveis.</p>
<p><strong>Exercício regular de direitos:</strong> preservar evidências de contratação, aceite, pagamentos, prevenção e defesa em controvérsias.</p>
<p><strong>Legítimo interesse, quando cabível e após avaliação:</strong> segurança, prevenção de fraude e abuso, melhoria técnica e proteção da plataforma, sempre com observância da necessidade, expectativa legítima e direitos do titular.</p>
<p><strong>Consentimento:</strong> será utilizado quando essa for a base adequada, especialmente para tratamentos opcionais que dependam de escolha livre e informada, podendo ser revogado nos termos da lei.</p>
<h2>4. Compartilhamento e operadores</h2><p>Dados poderão ser compartilhados, no limite necessário, com fornecedores de hospedagem e infraestrutura, banco de dados, autenticação, e-mail, pagamento, prevenção a fraude, suporte e tecnologia. O Mercado Pago poderá atuar de forma independente quanto aos dados tratados em seu ambiente de pagamento. A relação de fornecedores será revisada conforme a arquitetura efetivamente utilizada.</p>
<h2>5. Transferência internacional</h2><p>Alguns fornecedores tecnológicos podem processar ou armazenar dados fora do Brasil. Quando houver transferência internacional de dados pessoais, a ESTIBORDO adotará mecanismo válido previsto na LGPD e na regulamentação da ANPD, conforme aplicável.</p>
<h2>6. Segurança</h2><p>São adotadas medidas técnicas e administrativas compatíveis com os riscos, incluindo autenticação server-side, hash de senhas, cookies de sessão HttpOnly e Secure em produção, controle de acesso administrativo, limitação de tentativas, registros de segurança e conexões criptografadas. Nenhum sistema é absolutamente imune a incidentes.</p>
<h2>7. Retenção</h2><p>Os dados são conservados apenas pelo tempo necessário às finalidades, obrigações legais e exercício regular de direitos. Após o encerramento da finalidade, serão eliminados ou anonimizados quando aplicável, ressalvadas as hipóteses legais de conservação. A ESTIBORDO manterá internamente critérios documentados de retenção por categoria de dado.</p>
<h2>8. Direitos do titular</h2><p>Nos termos da LGPD, o titular poderá solicitar, conforme aplicável: confirmação de tratamento; acesso; correção; anonimização, bloqueio ou eliminação de dados desnecessários, excessivos ou tratados em desconformidade; portabilidade nos termos da regulamentação; informação sobre compartilhamentos; informação sobre a possibilidade de não consentir e suas consequências; revogação do consentimento; eliminação de dados tratados com consentimento, ressalvadas hipóteses legais; e revisão ou informações sobre decisões unicamente automatizadas, quando cabível.</p>
<h2>9. Como exercer direitos</h2><p>Solicitações podem ser feitas pelo canal estibordopscpp@gmail.com. Poderemos solicitar informações razoáveis para confirmar a identidade do requerente e proteger a conta contra fraude. O atendimento será gratuito nos casos previstos em lei.</p>
<h2>10. Crianças e adolescentes</h2><p>A plataforma é direcionada à preparação profissional e não é desenhada especificamente para crianças. Caso seja identificado tratamento envolvendo criança ou adolescente, serão aplicadas as salvaguardas legais pertinentes e o princípio do melhor interesse.</p>
<h2>11. Cookies</h2><p>Cookies e tecnologias equivalentes são tratados conforme a <a href="/politica-de-cookies">Política de Cookies</a>. Tecnologias opcionais baseadas em consentimento, se implementadas, deverão permanecer desativadas até escolha válida do usuário.</p>
<h2>12. Incidentes de segurança</h2><p>Incidentes serão avaliados e documentados. Quando presentes os requisitos legais e regulatórios, a ESTIBORDO realizará as comunicações cabíveis à ANPD e aos titulares afetados dentro dos prazos aplicáveis.</p>
<h2>13. Alterações</h2><p>Esta Política poderá ser atualizada para refletir mudanças legais, regulatórias ou técnicas. Alterações relevantes serão destacadas e poderão exigir nova manifestação do usuário quando a lei assim determinar.</p>
<div className={styles.links}><a href="/termos-de-uso">Termos</a><a href="/politica-de-cookies">Cookies</a><a href="/cancelamento-e-reembolso">Cancelamento e reembolso</a></div>
</article></main><Footer/></>;}