import {Nav,Footer} from "../components";import styles from "../legal.module.css";export const metadata={title:"Política de Privacidade"};
export default function Page(){return <><Nav/><main className={styles.page}><article className={styles.wrap}>
<span className={styles.eyebrow}>ESTIBORDO • PRIVACIDADE</span><h1>Política de Privacidade</h1><p className={styles.updated}>Versão vigente: 12 de setembro de 2026.</p>
<p>A ESTIBORDO utiliza dados pessoais somente na medida necessária para disponibilizar a conta, as ferramentas de estudo, pagamentos, suporte e segurança da plataforma, observando a legislação brasileira aplicável.</p>
<h2>1. Quais dados podem ser utilizados</h2><p>Conforme os recursos utilizados, podemos tratar nome, e-mail, CPF, telefone, endereço, informações profissionais ou marítimas fornecidas voluntariamente, dados necessários à contratação, registros de pagamento, progresso de estudo, respostas e desempenho, conteúdo inserido pelo próprio usuário e informações técnicas necessárias à autenticação e segurança. CPF, telefone e endereço recebem controles técnicos adicionais de proteção no armazenamento.</p>
<h2>2. Para que utilizamos esses dados</h2><p>Os dados são utilizados para criar e proteger a conta, liberar o acesso contratado, salvar progresso, fornecer simulados e demais ferramentas de estudo, personalizar funcionalidades, processar pagamentos, prestar suporte, prevenir fraude e abuso e cumprir obrigações legais quando aplicáveis.</p>
<h2>3. Autenticação e prevenção de abuso</h2><p>Podemos utilizar verificação de e-mail, autenticação em duas etapas, provedores de identidade como Google e serviços de prevenção automatizada contra abuso e cadastros maliciosos. Quando o usuário opta por entrar com Google, recebemos apenas os dados autorizados e necessários ao login, como identificador da conta, nome e e-mail verificado.</p><h2>4. Pagamentos</h2><p>O pagamento é processado por provedor especializado. A ESTIBORDO pode receber informações como identificação da transação, valor e status do pagamento, mas não armazena diretamente os dados completos do cartão informados no ambiente do provedor.</p>
<h2>5. Tutor e inteligência artificial</h2><p>Quando o usuário utiliza funcionalidades de inteligência artificial, a pergunta e o contexto necessário podem ser enviados ao serviço tecnológico responsável pela geração da resposta. O histórico pode ser mantido na conta para continuidade da conversa. Recomendamos não inserir dados pessoais sensíveis, segredos ou informações confidenciais desnecessárias.</p>
<h2>6. Compartilhamento</h2><p>Dados podem ser tratados por fornecedores tecnológicos necessários ao funcionamento da plataforma, como hospedagem, banco de dados, pagamento, autenticação, e-mail e inteligência artificial, sempre de acordo com a finalidade do serviço. Alguns desses fornecedores podem processar dados fora do Brasil, observadas as regras aplicáveis.</p>
<h2>7. Segurança e conservação</h2><p>A ESTIBORDO adota medidas técnicas para proteger contas e dados contra acessos indevidos. Os dados são mantidos pelo período necessário à prestação do serviço, ao cumprimento de obrigações legais e ao exercício regular de direitos e, quando aplicável, posteriormente eliminados ou anonimizados.</p>
<h2>8. Seus direitos</h2><p>O titular pode exercer os direitos previstos na LGPD, conforme aplicáveis, incluindo solicitar acesso, correção e eliminação de dados nas hipóteses legais. A própria plataforma também poderá disponibilizar recursos para exportar dados e excluir a conta.</p>
<h2>9. Contato</h2><p>Solicitações relacionadas à privacidade podem ser encaminhadas para <strong>estibordopscpp@gmail.com</strong>. Poderemos solicitar confirmação razoável da identidade para proteger a conta contra solicitações fraudulentas.</p>
<h2>10. Atualizações</h2><p>Esta Política poderá ser atualizada quando houver mudança relevante nas funcionalidades, no tratamento de dados ou na legislação aplicável.</p>
<div className={styles.links}><a href="/termos-de-uso">Termos de Uso</a><a href="/politica-de-cookies">Cookies</a><a href="/cancelamento-e-reembolso">Cancelamento e reembolso</a></div>
</article></main><Footer/></>;}