"use client";
export const ID=[1,0,0,1,0,0];
export const uid=p=>p+"_"+Math.random().toString(36).slice(2,9);
export const mul=(a,b)=>[a[0]*b[0]+a[2]*b[1],a[1]*b[0]+a[3]*b[1],a[0]*b[2]+a[2]*b[3],a[1]*b[2]+a[3]*b[3],a[0]*b[4]+a[2]*b[5]+a[4],a[1]*b[4]+a[3]*b[5]+a[5]];
export const translate=(x,y)=>[1,0,0,1,x,y];
export const scale=(x,y,cx=0,cy=0)=>mul(mul(translate(cx,cy),[x,0,0,y,0,0]),translate(-cx,-cy));
export const rotate=(rad,cx=0,cy=0)=>{const c=Math.cos(rad),s=Math.sin(rad);return mul(mul(translate(cx,cy),[c,s,-s,c,0,0]),translate(-cx,-cy))};
export const point=(m,p)=>({x:m[0]*p.x+m[2]*p.y+m[4],y:m[1]*p.x+m[3]*p.y+m[5]});
export function inverse(m){const d=m[0]*m[3]-m[1]*m[2];if(Math.abs(d)<1e-9)return ID;return [m[3]/d,-m[1]/d,-m[2]/d,m[0]/d,(m[2]*m[5]-m[3]*m[4])/d,(m[1]*m[4]-m[0]*m[5])/d]}
export function worldMatrix(item,byId){let m=item?.matrix||ID,p=item?.parentId?byId[item.parentId]:null,guard=0;while(p&&guard++<64){m=mul(p.matrix||ID,m);p=p.parentId?byId[p.parentId]:null}return m}
export function collectiveBounds(paths){const pts=[];for(const p of paths||[]){for(const n of p.nodes||[])pts.push({x:n.x,y:n.y},{x:n.x+n.inX,y:n.y+n.inY},{x:n.x+n.outX,y:n.y+n.outY})}if(!pts.length)return null;const xs=pts.map(p=>p.x),ys=pts.map(p=>p.y),x=Math.min(...xs),y=Math.min(...ys),r=Math.max(...xs),b=Math.max(...ys);return {x,y,w:r-x,h:b-y,right:r,bottom:b,cx:(x+r)/2,cy:(y+b)/2}}
function perpDistance(p,a,b){const dx=b.x-a.x,dy=b.y-a.y;if(!dx&&!dy)return Math.hypot(p.x-a.x,p.y-a.y);return Math.abs(dy*p.x-dx*p.y+b.x*a.y-b.y*a.x)/Math.hypot(dx,dy)}
function rdp(points,eps){if(points.length<3)return points;let max=0,idx=0;for(let i=1;i<points.length-1;i++){const d=perpDistance(points[i],points[0],points.at(-1));if(d>max){max=d;idx=i}}if(max>eps){const a=rdp(points.slice(0,idx+1),eps),b=rdp(points.slice(idx),eps);return [...a.slice(0,-1),...b]}return [points[0],points.at(-1)]}
export function simplifyNodes(nodes,eps=2){if((nodes||[]).length<4)return nodes||[];const anchors=rdp(nodes.map(n=>({x:n.x,y:n.y,src:n})),eps);return anchors.map(a=>({...a.src,x:a.x,y:a.y,inX:0,inY:0,outX:0,outY:0,smooth:false}))}
export function reverseNodes(nodes=[]){return [...nodes].reverse().map(n=>({...n,inX:-n.outX,inY:-n.outY,outX:-n.inX,outY:-n.inY}))}
export function splitNodes(nodes=[],idx=0){if(idx<=0||idx>=nodes.length-1)return null;return [nodes.slice(0,idx+1).map(n=>({...n})),nodes.slice(idx).map(n=>({...n}))]}
export function joinNodeSets(a=[],b=[]){if(!a.length)return b;if(!b.length)return a;const A=[...a.map(n=>({...n}))],B=[...b.map(n=>({...n}))],la=A.at(-1),fb=B[0];if(Math.hypot(la.x-fb.x,la.y-fb.y)<8){la.x=(la.x+fb.x)/2;la.y=(la.y+fb.y)/2;B.shift()}return [...A,...B]}
export function offsetNodes(nodes=[],distance=10){if(nodes.length<2)return nodes;const out=[];for(let i=0;i<nodes.length;i++){const a=nodes[Math.max(0,i-1)],b=nodes[Math.min(nodes.length-1,i+1)],dx=b.x-a.x,dy=b.y-a.y,l=Math.hypot(dx,dy)||1,nx=-dy/l,ny=dx/l;out.push({...nodes[i],x:nodes[i].x+nx*distance,y:nodes[i].y+ny*distance})}return out}
export function parseSvgText(text){const doc=new DOMParser().parseFromString(text,"image/svg+xml"),svg=doc.documentElement,vb=svg.getAttribute("viewBox")||"0 0 800 600",parts=vb.split(/[s,]+/).map(Number),paths=[];doc.querySelectorAll("path").forEach((p,i)=>paths.push({id:uid("path"),name:p.getAttribute("id")||`Imported ${i+1}`,kind:"path",parentId:"",nodes:[],d:p.getAttribute("d")||"",closed:/zs*$/i.test(p.getAttribute("d")||""),fill:p.getAttribute("fill")||"none",stroke:p.getAttribute("stroke")||"none",strokeWidth:Number(p.getAttribute("stroke-width")||1),opacity:Number(p.getAttribute("opacity")||1),fillRule:p.getAttribute("fill-rule")||"nonzero",visible:true,locked:false,matrix:ID}));return {id:uid("vec"),name:"SVG importado",width:parts[2]||800,height:parts[3]||600,viewBox:vb,paths,updatedAt:new Date().toISOString()}}
export function svgString(asset){const esc=s=>String(s||"").replace(/&/g,"&amp;").replace(/"/g,"&quot;");const body=(asset.paths||[]).filter(p=>p.visible!==false&&p.kind!=="group").map(p=>`<path d="${esc(p.d)}" fill="${esc(p.fill||"none")}" stroke="${esc(p.stroke||"none")}" stroke-width="${Number(p.strokeWidth)||0}" stroke-linecap="${esc(p.strokeCap||"butt")}" stroke-linejoin="${esc(p.strokeJoin||"miter")}" opacity="${p.opacity??1}" fill-rule="${esc(p.fillRule||"nonzero")}" transform="matrix(${(p.matrix||ID).join(" ")})"/>`).join("");return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${esc(asset.viewBox||`0 0 ${asset.width} ${asset.height}`)}">${body}</svg>`}
