"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import EditorSDK from "./EditorStudioSDK";
import {selectorForNode} from "./EditorObjectRegistry";

const TABS=[["layout","Layout"],["style","Style"],["responsive","Responsive"],["motion","Motion"],["tokens","Tokens"],["code","Code"],["versions","Versions"],["audit","Audit"],["plugins","Plugins"]];
const STYLE_FIELDS={layout:["display","position","width","height","minWidth","maxWidth","minHeight","maxHeight","gap","padding","margin","overflow","zIndex"],style:["color","backgroundColor","borderRadius","borderWidth","borderColor","boxShadow","opacity","filter","transform","mixBlendMode","clipPath"]};
function frame(){return document.querySelector('iframe[title="Prévia da página"]')}
function safeParse(v,fallback){try{return JSON.parse(v)}catch{return fallback}}
function clone(v){return JSON.parse(JSON.stringify(v))}
function route(){try{return frame()?.contentWindow?.location?.pathname||frame()?.getAttribute("src")?.split("?")[0]||"/"}catch{return "/"}}
function selectedNode(){try{return frame()?.contentDocument?.querySelector("[data-editor-core-selected],[data-ev-selected]")||null}catch{return null}}
function field(label,value,onChange,placeholder=""){return <label className="emx-field"><span>{label}</span><input value={value||""} placeholder={placeholder} onChange={e=>onChange(e.target.value)}/></label>}
function select(label,value,onChange,options){return <label className="emx-field"><span>{label}</span><select value={value||""} onChange={e=>onChange(e.target.value)}>{options.map(x=><option key={x} value={x}>{x}</option>)}</select></label>}
function currentConfig(design,page,selector){return design?.pages?.[page]?.elements?.[selector]||{}}

export default function EditorMaxSuite(){
  const [open,setOpen]=useState(false),[tab,setTab]=useState("layout"),[design,setDesign]=useState(null),[sha,setSha]=useState(""),[page,setPage]=useState("/"),[selector,setSelector]=useState(""),[nodeInfo,setNodeInfo]=useState(null),[dirty,setDirty]=useState(false),[saving,setSaving]=useState(false),[status,setStatus]=useState(""),[bp,setBp]=useState("desktop"),[versions,setVersions]=useState([]),[audit,setAudit]=useState([]),[history,setHistory]=useState([]),[historyIndex,setHistoryIndex]=useState(-1),[customBpName,setCustomBpName]=useState("Laptop"),[customBpWidth,setCustomBpWidth]=useState("1280");
  const lastSelection=useRef("");
  const cfg=useMemo(()=>currentConfig(design,page,selector),[design,page,selector]);
  const style=bp==="desktop"?(cfg.style||{}):(cfg.responsive?.[bp]?.style||{});
  const breakpoints=design?.global?.breakpoints||{tablet:1024,mobile:620,custom:[]};

  async function load(){try{const r=await fetch("/api/site-editor/design",{cache:"no-store"}),j=await r.json();if(j.ok){setDesign(j.content);setSha(j.sha||"");setStatus("Design carregado")}}catch{setStatus("Falha ao carregar design")}}
  useEffect(()=>{load()},[]);
  useEffect(()=>{const id=setInterval(()=>{const n=selectedNode();if(!n)return;const s=selectorForNode(n);if(!s||s===lastSelection.current)return;lastSelection.current=s;setSelector(s);setPage(route());const r=n.getBoundingClientRect();setNodeInfo({tag:n.tagName,id:n.getAttribute("data-editor-id")||n.id||"",className:String(n.className||"").slice(0,180),width:Math.round(r.width),height:Math.round(r.height),text:(n.textContent||"").trim().slice(0,120)});EditorSDK.emit("selection",{selector:s,route:route(),node:n})},350);return()=>clearInterval(id)},[]);
  useEffect(()=>{if(!design||!dirty)return;const id=setTimeout(()=>{try{localStorage.setItem("estibordo-max-draft",JSON.stringify({at:Date.now(),design,sha}))}catch{}},500);return()=>clearTimeout(id)},[design,dirty,sha]);

  function push(next,label){if(!design)return;const before=clone(design);const after=typeof next==="function"?next(clone(design)):next;const tx=EditorSDK.transaction(label,before,after,{page,selector,bp});const nextHistory=[...history.slice(0,historyIndex+1),tx].slice(-80);setHistory(nextHistory);setHistoryIndex(nextHistory.length-1);setDesign(after);setDirty(true);setStatus(label);postPreview(after)}
  function postPreview(next){try{frame()?.contentWindow?.postMessage({type:"estibordo-editor-design",design:next},window.location.origin)}catch{}}
  function mutateElement(fn,label){if(!selector)return setStatus("Selecione um objeto primeiro");push(d=>{d.pages||={};d.pages[page]||={elements:{},blocks:[],settings:{},customCode:{}};d.pages[page].elements||={};const c=clone(d.pages[page].elements[selector]||{});fn(c);d.pages[page].elements[selector]=c;return d},label)}
  function setStyle(key,value){mutateElement(c=>{if(bp==="desktop"){c.style={...(c.style||{}),[key]:value}}else{c.responsive={...(c.responsive||{})};c.responsive[bp]={...(c.responsive[bp]||{}),style:{...(c.responsive[bp]?.style||{}),[key]:value}}}},`Style: ${key}`)}
  function setAttr(key,value){mutateElement(c=>{c.attrs={...(c.attrs||{}),[key]:value}},`Conteúdo: ${key}`)}
  function setMotion(key,value){mutateElement(c=>{c.motion={...(c.motion||{}),[key]:value}},`Motion: ${key}`)}
  function undo(){if(historyIndex<0)return;const tx=history[historyIndex];setDesign(clone(tx.before));setHistoryIndex(historyIndex-1);setDirty(true);postPreview(tx.before);setStatus("Undo: "+tx.label)}
  function redo(){if(historyIndex>=history.length-1)return;const tx=history[historyIndex+1];setDesign(clone(tx.after));setHistoryIndex(historyIndex+1);setDirty(true);postPreview(tx.after);setStatus("Redo: "+tx.label)}
  async function save(){if(!design||saving)return;setSaving(true);setStatus("Publicando design…");try{const r=await fetch("/api/site-editor/design/save",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({content:design,sha})}),j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||"Falha ao salvar");setSha(j.sha||sha);setDirty(false);snapshot("Publicação");setStatus("Publicado com sucesso") }catch(e){setStatus(e.message||"Erro ao publicar")}finally{setSaving(false)}}
  function snapshot(name="Snapshot"){if(!design)return;const item={id:Date.now().toString(36),name,at:Date.now(),page,design:clone(design)};const list=[item,...versions].slice(0,20);setVersions(list);try{localStorage.setItem("estibordo-max-versions",JSON.stringify(list))}catch{}}
  useEffect(()=>{try{setVersions(safeParse(localStorage.getItem("estibordo-max-versions")||"[]",[]))}catch{}},[]);
  function restoreVersion(v){if(!v?.design)return;push(clone(v.design),"Versão restaurada: "+v.name)}
  function addBreakpoint(){const width=Math.max(320,Math.min(7680,Number(customBpWidth)||1280)),id="bp_"+customBpName.toLowerCase().replace(/[^a-z0-9]+/g,"_")+"_"+Math.random().toString(36).slice(2,5);push(d=>{d.global||={};d.global.breakpoints={tablet:1024,mobile:620,custom:[],...(d.global.breakpoints||{})};d.global.breakpoints.custom=[...(d.global.breakpoints.custom||[]),{id,label:customBpName,maxWidth:width}];return d},"Breakpoint criado")}
  function setToken(key,value){push(d=>{d.global||={};d.global.designSystem={...(d.global.designSystem||{}),[key]:value};return d},"Token: "+key)}
  function runAudit(){const doc=frame()?.contentDocument,issues=[];if(!doc)return;doc.querySelectorAll("img").forEach((n,i)=>{if(!n.alt)issues.push({level:"error",title:"Imagem sem ALT",detail:`Imagem ${i+1}`})});const h1=doc.querySelectorAll("h1").length;if(h1!==1)issues.push({level:"warn",title:"Estrutura H1",detail:`Encontrados ${h1} H1`});const w=doc.documentElement.clientWidth;const overflow=[...doc.querySelectorAll("body *")].filter(n=>{const r=n.getBoundingClientRect();return r.width>2&&(r.right>w+3||r.left<-3)});if(overflow.length)issues.push({level:"error",title:"Overflow horizontal",detail:`${overflow.length} elementos fora da viewport`});doc.querySelectorAll("button,a,input,select,textarea").forEach(n=>{const r=n.getBoundingClientRect();if(r.width&&r.height&&(r.width<40||r.height<40))issues.push({level:"warn",title:"Touch target pequeno",detail:(n.textContent||n.getAttribute("aria-label")||n.tagName).slice(0,50)})});const nodes=doc.querySelectorAll("*").length;if(nodes>2200)issues.push({level:"warn",title:"DOM pesado",detail:`${nodes} nós`});setAudit(issues.length?issues:[{level:"ok",title:"Auditoria aprovada",detail:"Nenhum problema crítico detectado"}]);setTab("audit")}
  function quickLayout(type){const presets={row:{display:"flex",flexDirection:"row",alignItems:"center",gap:"16px"},column:{display:"flex",flexDirection:"column",gap:"16px"},grid2:{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:"16px"},grid3:{display:"grid",gridTemplateColumns:"repeat(3,minmax(0,1fr))",gap:"16px"},center:{display:"grid",placeItems:"center"},free:{position:"relative"},sticky:{position:"sticky",top:"0px",zIndex:"20"}};const p=presets[type];if(!p)return;mutateElement(c=>{const target=bp==="desktop"?(c.style||={}):((c.responsive||={})[bp]||={style:{}}).style;Object.assign(target,p)},"Layout preset: "+type)}
  function setCustomCode(key,value){push(d=>{d.pages||={};d.pages[page]||={elements:{},blocks:[],settings:{},customCode:{}};d.pages[page].customCode={...(d.pages[page].customCode||{}),[key]:value};return d},"Código customizado")}

  return <>
    <button className="emx-launch" onClick={()=>setOpen(true)} title="Editor Studio MAX">MAX</button>
    {open&&<aside className="emx-panel"><header><div><b>ESTIBORDO STUDIO MAX</b><span>Design system · layout · motion · versions</span></div><button onClick={()=>setOpen(false)}>×</button></header>
      <div className="emx-selection"><div><b>{nodeInfo?`${nodeInfo.tag} · ${nodeInfo.width}×${nodeInfo.height}`:"Nenhum elemento selecionado"}</b><span>{selector||"Clique em um objeto no canvas"}</span></div><div className="emx-history"><button onClick={undo} disabled={historyIndex<0}>↶</button><button onClick={redo} disabled={historyIndex>=history.length-1}>↷</button></div></div>
      <nav>{TABS.map(([id,label])=><button key={id} className={tab===id?"on":""} onClick={()=>setTab(id)}>{label}</button>)}</nav>
      <div className="emx-scroll">
        {(tab==="layout"||tab==="style")&&<section><h4>{tab.toUpperCase()} · {bp}</h4>{tab==="layout"&&<div className="emx-presets">{[["row","Flex Row"],["column","Flex Column"],["grid2","Grid 2"],["grid3","Grid 3"],["center","Center"],["free","Free"],["sticky","Sticky"]].map(([id,l])=><button key={id} onClick={()=>quickLayout(id)}>{l}</button>)}</div>}{STYLE_FIELDS[tab].map(k=>field(k,style[k],v=>setStyle(k,v)))}{selector&&<><h4>CONTENT</h4>{field("text",cfg.attrs?.text,v=>setAttr("text",v))}{field("href",cfg.attrs?.href,v=>setAttr("href",v))}{field("alt",cfg.attrs?.alt,v=>setAttr("alt",v))}</>}</section>}
        {tab==="responsive"&&<section><h4>BREAKPOINTS</h4><div className="emx-bps">{[["desktop","Desktop"],...(breakpoints.custom||[]).map(x=>[x.id,`${x.label} ≤ ${x.maxWidth}px`]),["tablet",`Tablet ≤ ${breakpoints.tablet}px`],["mobile",`Mobile ≤ ${breakpoints.mobile}px`]].map(([id,l])=><button key={id} className={bp===id?"on":""} onClick={()=>setBp(id)}>{l}</button>)}</div><div className="emx-grid2">{field("Nome",customBpName,setCustomBpName)}{field("Max px",customBpWidth,setCustomBpWidth)}</div><button className="emx-wide" onClick={addBreakpoint}>＋ Criar breakpoint</button><p>As propriedades do breakpoint atual sobrescrevem a base sem destruir os demais dispositivos.</p></section>}
        {tab==="motion"&&<section><h4>MOTION & INTERACTIONS</h4>{select("Trigger",cfg.motion?.trigger||"load",v=>setMotion("trigger",v),["load","scroll","hover"])}{select("Entrada",cfg.motion?.entrance||"none",v=>setMotion("entrance",v),["none","fade","slide-up","slide-left","slide-right","zoom","rotate"])}{select("Hover",cfg.motion?.hover||"none",v=>setMotion("hover",v),["none","lift","zoom","glow","tilt","fade"])}{select("Click",cfg.motion?.click||"none",v=>setMotion("click",v),["none","pulse","shake","pop"])}<div className="emx-grid2">{field("Duration ms",cfg.motion?.duration||"500",v=>setMotion("duration",v))}{field("Delay ms",cfg.motion?.delay||"0",v=>setMotion("delay",v))}</div><div className="emx-timeline"><i/><i/><i/><i/></div></section>}
        {tab==="tokens"&&<section><h4>DESIGN TOKENS</h4>{["primary","accent","surface","text","radius","maxContentWidth","fontFamily","h1","body"].map(k=>field(k,design?.global?.designSystem?.[k],v=>setToken(k,v)))}<h4>CSS VARIABLES · JSON</h4><textarea value={JSON.stringify(design?.global?.designSystem?.variables||{},null,2)} onChange={e=>{const vars=safeParse(e.target.value,null);if(vars)setToken("variables",vars)}}/></section>}
        {tab==="code"&&<section><h4>PAGE CSS</h4><textarea value={design?.pages?.[page]?.customCode?.css||""} onChange={e=>setCustomCode("css",e.target.value)} placeholder=".minha-classe { ... }"/><h4>SAFE HTML</h4><textarea value={design?.pages?.[page]?.customCode?.html||""} onChange={e=>setCustomCode("html",e.target.value)} placeholder="<section>...</section>"/></section>}
        {tab==="versions"&&<section><h4>VERSIONS & RECOVERY</h4><div className="emx-actions"><button onClick={()=>snapshot("Snapshot manual")}>Snapshot</button><button onClick={()=>{const d=safeParse(localStorage.getItem("estibordo-max-draft")||"",null);if(d?.design)push(d.design,"Draft local restaurado")}}>Restore Draft</button></div><div className="emx-versions">{versions.map(v=><button key={v.id} onClick={()=>restoreVersion(v)}><b>{v.name}</b><span>{new Date(v.at).toLocaleString("pt-BR")}</span></button>)}</div></section>}
        {tab==="audit"&&<section><h4>QUALITY GATE</h4><button className="emx-wide" onClick={runAudit}>Executar auditoria</button><div className="emx-audit">{audit.map((x,i)=><article key={i} className={x.level}><b>{x.title}</b><span>{x.detail}</span></article>)}</div></section>}
        {tab==="plugins"&&<section><h4>PLUGIN SDK</h4><p>Arquitetura extensível ativa. Plugins podem registrar adapters, comandos e ferramentas sem alterar o núcleo.</p><div className="emx-plugins">{EditorSDK.plugins.map(p=><article key={p.id}><b>{p.name}</b><span>{p.id} · v{p.version}</span></article>)}</div><h4>COMMANDS</h4><div className="emx-commands">{EditorSDK.commands.map(c=><button key={c.id} onClick={()=>c.run?.()}>{c.title||c.id}</button>)}</div></section>}
      </div>
      <footer><div><b className={dirty?"dirty":"saved"}>{dirty?"● Alterações no MAX":"✓ Sincronizado"}</b><span>{status}</span></div><button onClick={runAudit}>Audit</button><button className="primary" disabled={!dirty||saving} onClick={save}>{saving?"Publicando…":"Salvar & publicar"}</button></footer>
    </aside>}
  </>
}