"use client";
export const uid=p=>p+"_"+Math.random().toString(36).slice(2,9);
export const clone=v=>JSON.parse(JSON.stringify(v));
export function pathD(nodes=[],closed=false){if(!nodes.length)return "";let d=`M ${nodes[0].x.toFixed(2)} ${nodes[0].y.toFixed(2)}`;for(let i=1;i<nodes.length;i++){const a=nodes[i-1],b=nodes[i];d+=` C ${(a.x+a.outX).toFixed(2)} ${(a.y+a.outY).toFixed(2)} ${(b.x+b.inX).toFixed(2)} ${(b.y+b.inY).toFixed(2)} ${b.x.toFixed(2)} ${b.y.toFixed(2)}`}if(closed&&nodes.length>1){const a=nodes.at(-1),b=nodes[0];d+=` C ${(a.x+a.outX).toFixed(2)} ${(a.y+a.outY).toFixed(2)} ${(b.x+b.inX).toFixed(2)} ${(b.y+b.inY).toFixed(2)} ${b.x.toFixed(2)} ${b.y.toFixed(2)} Z`}return d}
export function normalizeAsset(input){const a=clone(input||{});a.id=a.id||uid("vec");a.name=a.name||"Novo vetor";a.width=Math.max(1,Number(a.width)||800);a.height=Math.max(1,Number(a.height)||600);a.viewBox=a.viewBox||`0 0 ${a.width} ${a.height}`;a.guides=Array.isArray(a.guides)?a.guides:[];a.paths=Array.isArray(a.paths)?a.paths:[];if(a.nodes?.length&&!a.paths.some(p=>p.nodes?.length)){a.paths.unshift({id:uid("path"),name:"Path 1",kind:"path",nodes:clone(a.nodes),closed:Boolean(a.closed),fill:"none",stroke:"#e5e7eb",strokeWidth:2,opacity:1,visible:true,locked:false})}a.paths=a.paths.map((p,i)=>({...p,id:p.id||uid("path"),name:p.name||`Layer ${i+1}`,kind:p.kind||"path",parentId:p.parentId||"",children:Array.isArray(p.children)?p.children:[],matrix:Array.isArray(p.matrix)&&p.matrix.length===6?p.matrix:[1,0,0,1,0,0],nodes:Array.isArray(p.nodes)?p.nodes:[],closed:Boolean(p.closed),visible:p.visible!==false,locked:Boolean(p.locked),fill:p.fill??"none",stroke:p.stroke??"#e5e7eb",strokeWidth:Number(p.strokeWidth??0),strokeCap:p.strokeCap||"butt",strokeJoin:p.strokeJoin||"miter",strokeDash:Array.isArray(p.strokeDash)?p.strokeDash:[],opacity:Number(p.opacity??1),fillRule:p.fillRule||"nonzero",d:p.nodes?.length?pathD(p.nodes,p.closed):(p.d||"")}));delete a.nodes;delete a.closed;return a}
export function boundsOfNodes(nodes=[]){if(!nodes.length)return null;let x=Infinity,y=Infinity,r=-Infinity,b=-Infinity;for(const n of nodes){for(const p of [[n.x,n.y],[n.x+n.inX,n.y+n.inY],[n.x+n.outX,n.y+n.outY]]){x=Math.min(x,p[0]);y=Math.min(y,p[1]);r=Math.max(r,p[0]);b=Math.max(b,p[1])}}return {x,y,w:r-x,h:b-y,right:r,bottom:b,cx:(x+r)/2,cy:(y+b)/2}}
export function boundsOfPath(p){return boundsOfNodes(p?.nodes||[])||{x:0,y:0,w:0,h:0,right:0,bottom:0,cx:0,cy:0}}
export function translatePath(p,dx,dy){for(const n of p.nodes||[]){n.x+=dx;n.y+=dy}p.d=pathD(p.nodes,p.closed);return p}
export function scalePath(p,sx,sy,b){const o={x:b.cx,y:b.cy};for(const n of p.nodes||[]){n.x=o.x+(n.x-o.x)*sx;n.y=o.y+(n.y-o.y)*sy;n.inX*=sx;n.inY*=sy;n.outX*=sx;n.outY*=sy}p.d=pathD(p.nodes,p.closed);return p}
export function rotatePath(p,rad,b){const o={x:b.cx,y:b.cy},c=Math.cos(rad),s=Math.sin(rad),rot=(x,y)=>({x:x*c-y*s,y:x*s+y*c});for(const n of p.nodes||[]){let q=rot(n.x-o.x,n.y-o.y);n.x=o.x+q.x;n.y=o.y+q.y;q=rot(n.inX,n.inY);n.inX=q.x;n.inY=q.y;q=rot(n.outX,n.outY);n.outX=q.x;n.outY=q.y}p.d=pathD(p.nodes,p.closed);return p}
export class SpatialHash{constructor(cell=96){this.cell=cell;this.map=new Map()}clear(){this.map.clear()}keys(b){const out=[];for(let x=Math.floor(b.x/this.cell);x<=Math.floor(b.right/this.cell);x++)for(let y=Math.floor(b.y/this.cell);y<=Math.floor(b.bottom/this.cell);y++)out.push(x+":"+y);return out}insert(id,b){for(const k of this.keys(b)){if(!this.map.has(k))this.map.set(k,new Set());this.map.get(k).add(id)}}queryPoint(x,y,r=0){const out=new Set(),b={x:x-r,y:y-r,right:x+r,bottom:y+r};for(const k of this.keys(b))for(const id of this.map.get(k)||[])out.add(id);return [...out]}}
export function rebuildIndex(asset,index){index.clear();for(const p of asset.paths||[]){if(p.visible===false||p.kind!=="path")continue;const b=boundsOfPath(p);if(b.w||b.h)index.insert(p.id,b)}return index}
export function snapDelta(asset,ids,dx,dy,t=6){const moving=(asset.paths||[]).filter(p=>ids.includes(p.id)).map(boundsOfPath);if(!moving.length)return {dx,dy,guides:[]};const others=(asset.paths||[]).filter(p=>!ids.includes(p.id)&&p.visible!==false&&p.kind==="path").map(boundsOfPath),guides=[];let bx=t+1,by=t+1,sx=dx,sy=dy;for(const m of moving)for(const o of others){for(const a of [m.x+dx,m.cx+dx,m.right+dx])for(const b of [o.x,o.cx,o.right]){const d=b-a;if(Math.abs(d)<Math.abs(bx)&&Math.abs(d)<=t){bx=d;sx=dx+d;guides.push({axis:"x",v:b})}}for(const a of [m.y+dy,m.cy+dy,m.bottom+dy])for(const b of [o.y,o.cy,o.bottom]){const d=b-a;if(Math.abs(d)<Math.abs(by)&&Math.abs(d)<=t){by=d;sy=dy+d;guides.push({axis:"y",v:b})}}}return {dx:sx,dy:sy,guides:guides.slice(-2)}}
export function booleanPath(op,paths=[]){const src=paths.filter(Boolean);return {id:uid("bool"),name:op[0].toUpperCase()+op.slice(1),kind:"path",nodes:[],closed:true,d:"",fill:src[0]?.fill||"#ffffff",stroke:src[0]?.stroke||"none",strokeWidth:src[0]?.strokeWidth||0,opacity:1,fillRule:op==="exclude"?"evenodd":"nonzero",visible:true,locked:false,matrix:[1,0,0,1,0,0],boolean:{op,sources:src.map(p=>p.id)}}}
export function groupPaths(asset,ids,kind="group"){const id=uid(kind),group={id,name:kind==="frame"?"Frame":"Group",kind,parentId:"",children:[...ids],matrix:[1,0,0,1,0,0],visible:true,locked:false,opacity:1,nodes:[],d:""};for(const p of asset.paths||[])if(ids.includes(p.id))p.parentId=id;asset.paths.push(group);return group}
export function ungroup(asset,id){const g=asset.paths.find(p=>p.id===id);if(!g)return;for(const p of asset.paths)if(p.parentId===id)p.parentId=g.parentId||"";asset.paths=asset.paths.filter(p=>p.id!==id)}
