"use client";
import {useEffect,useMemo,useRef,useState} from "react";

const clone=v=>JSON.parse(JSON.stringify(v));
const uid=p=>p+"_"+Math.random().toString(36).slice(2,9);
function emptyAsset(){return {id:uid("vec"),name:"Novo vetor",width:800,height:600,viewBox:"0 0 800 600",closed:false,nodes:[],paths:[],updatedAt:new Date().toISOString()}}
function dFromNodes(nodes,closed){if(!nodes?.length)return "";let d=`M ${nodes[0].x.toFixed(2)} ${nodes[0].y.toFixed(2)}`;for(let i=1;i<nodes.length;i++){const a=nodes[i-1],b=nodes[i];d+=` C ${(a.x+a.outX).toFixed(2)} ${(a.y+a.outY).toFixed(2)} ${(b.x+b.inX).toFixed(2)} ${(b.y+b.inY).toFixed(2)} ${b.x.toFixed(2)} ${b.y.toFixed(2)}`}if(closed&&nodes.length>1){const a=nodes.at(-1),b=nodes[0];d+=` C ${(a.x+a.outX).toFixed(2)} ${(a.y+a.outY).toFixed(2)} ${(b.x+b.inX).toFixed(2)} ${(b.y+b.inY).toFixed(2)} ${b.x.toFixed(2)} ${b.y.toFixed(2)} Z`}return d}
function assetWithPath(a){const next=clone(a),d=dFromNodes(next.nodes,next.closed),base=next.paths?.[0]||{id:uid("path"),fill:"none",stroke:"#e5e7eb",strokeWidth:2,opacity:1,fillRule:"nonzero"};next.paths=[{...base,d},...(next.paths||[]).slice(1)];next.viewBox=`0 0 ${next.width} ${next.height}`;next.updatedAt=new Date().toISOString();return next}
function near(a,b,r=10){return Math.hypot(a.x-b.x,a.y-b.y)<=r}

export default function EditorVectorWorkspace({asset,onClose,onSave,onInsert}){
  const [doc,setDoc]=useState(()=>assetWithPath(asset?clone(asset):emptyAsset())),[tool,setTool]=useState("pen"),[selected,setSelected]=useState(-1),[handle,setHandle]=useState("anchor"),[zoom,setZoom]=useState(1),[pan,setPan]=useState({x:40,y:40}),[fill,setFill]=useState(asset?.paths?.[0]?.fill||"none"),[stroke,setStroke]=useState(asset?.paths?.[0]?.stroke||"#e5e7eb"),[strokeWidth,setStrokeWidth]=useState(asset?.paths?.[0]?.strokeWidth||2);
  const canvas=useRef(null),drag=useRef(null),dirty=useRef(true),raf=useRef(0),cache=useRef({key:"",path:null}),space=useRef(false);
  useEffect(()=>{setDoc(assetWithPath(asset?clone(asset):emptyAsset()));setSelected(-1)},[asset?.id]);
  useEffect(()=>{dirty.current=true},[doc,tool,selected,zoom,pan,fill,stroke,strokeWidth]);

  function screenToWorld(e){const r=canvas.current.getBoundingClientRect();return {x:(e.clientX-r.left-pan.x)/zoom,y:(e.clientY-r.top-pan.y)/zoom}}
  function findPoint(p){let best=null;doc.nodes.forEach((n,i)=>{const pts=[["anchor",{x:n.x,y:n.y}],["in",{x:n.x+n.inX,y:n.y+n.inY}],["out",{x:n.x+n.outX,y:n.y+n.outY}]];for(const [h,q] of pts)if(near(p,q,9/zoom)&&(!best||Math.hypot(p.x-q.x,p.y-q.y)<best.dist))best={i,h,dist:Math.hypot(p.x-q.x,p.y-q.y)}});return best}
  function mutate(fn){setDoc(cur=>{const n=clone(cur);fn(n);return assetWithPath(n)})}
  function draw(){
    if(!dirty.current)return;dirty.current=false;const c=canvas.current;if(!c)return,ctx=c.getContext("2d");const rect=c.getBoundingClientRect(),dpr=Math.min(3,window.devicePixelRatio||1),w=Math.max(1,Math.round(rect.width*dpr)),h=Math.max(1,Math.round(rect.height*dpr));if(c.width!==w||c.height!==h){c.width=w;c.height=h}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,rect.width,rect.height);ctx.fillStyle="#0b1220";ctx.fillRect(0,0,rect.width,rect.height);
    ctx.save();ctx.translate(pan.x,pan.y);ctx.scale(zoom,zoom);
    const step=50;ctx.lineWidth=1/zoom;ctx.strokeStyle="rgba(148,163,184,.11)";ctx.beginPath();for(let x=0;x<=doc.width;x+=step){ctx.moveTo(x,0);ctx.lineTo(x,doc.height)}for(let y=0;y<=doc.height;y+=step){ctx.moveTo(0,y);ctx.lineTo(doc.width,y)}ctx.stroke();ctx.strokeStyle="rgba(148,163,184,.45)";ctx.strokeRect(0,0,doc.width,doc.height);
    const d=doc.paths?.[0]?.d||"";if(d){const key=d+"|"+fill+"|"+stroke+"|"+strokeWidth;if(cache.current.key!==key){cache.current={key,path:new Path2D(d)}}const p=cache.current.path;if(fill&&fill!=="none"){ctx.fillStyle=fill;ctx.fill(p,doc.paths?.[0]?.fillRule||"nonzero")}if(stroke&&stroke!=="none"&&strokeWidth>0){ctx.strokeStyle=stroke;ctx.lineWidth=strokeWidth;ctx.stroke(p)}}
    if(tool!=="preview"){doc.nodes.forEach((n,i)=>{const active=i===selected;ctx.lineWidth=1/zoom;ctx.strokeStyle=active?"#a78bfa":"#64748b";ctx.beginPath();ctx.moveTo(n.x+n.inX,n.y+n.inY);ctx.lineTo(n.x,n.y);ctx.lineTo(n.x+n.outX,n.y+n.outY);ctx.stroke();for(const [h,x,y] of [["in",n.x+n.inX,n.y+n.inY],["out",n.x+n.outX,n.y+n.outY]]){ctx.fillStyle=active&&handle===h?"#f0abfc":"#cbd5e1";ctx.beginPath();ctx.arc(x,y,4/zoom,0,Math.PI*2);ctx.fill()}ctx.fillStyle=active?"#8b5cf6":"#f8fafc";ctx.strokeStyle="#0f172a";ctx.lineWidth=1/zoom;ctx.beginPath();ctx.rect(n.x-5/zoom,n.y-5/zoom,10/zoom,10/zoom);ctx.fill();ctx.stroke()})}
    ctx.restore();
  }
  useEffect(()=>{const loop=()=>{draw();raf.current=requestAnimationFrame(loop)};raf.current=requestAnimationFrame(loop);return()=>cancelAnimationFrame(raf.current)},[doc,tool,selected,zoom,pan,fill,stroke,strokeWidth]);
  useEffect(()=>{const k=e=>{if(e.code==="Space")space.current=e.type==="keydown";if(e.type==="keydown"&&e.key==="Delete"&&selected>=0){mutate(d=>d.nodes.splice(selected,1));setSelected(-1)}if(e.type==="keydown"&&(e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="z"){e.preventDefault()}};window.addEventListener("keydown",k);window.addEventListener("keyup",k);return()=>{window.removeEventListener("keydown",k);window.removeEventListener("keyup",k)}},[selected]);

  function down(e){const p=screenToWorld(e);if(space.current||e.button===1){drag.current={kind:"pan",x:e.clientX,y:e.clientY,pan:{...pan}};canvas.current.setPointerCapture?.(e.pointerId);return}
    const hit=findPoint(p);if(hit){setSelected(hit.i);setHandle(hit.h);drag.current={kind:"point",i:hit.i,h:hit.h,start:p,node:clone(doc.nodes[hit.i])};canvas.current.setPointerCapture?.(e.pointerId);return}
    if(tool==="pen"){const node={x:p.x,y:p.y,inX:0,inY:0,outX:0,outY:0,smooth:true};mutate(d=>d.nodes.push(node));setSelected(doc.nodes.length);setHandle("out");drag.current={kind:"new",i:doc.nodes.length,start:p};canvas.current.setPointerCapture?.(e.pointerId)}else setSelected(-1)
  }
  function move(e){if(!drag.current)return;const op=drag.current;if(op.kind==="pan"){setPan({x:op.pan.x+e.clientX-op.x,y:op.pan.y+e.clientY-op.y});return}const p=screenToWorld(e);if(op.kind==="new"){mutate(d=>{const n=d.nodes[op.i];if(!n)return;n.outX=p.x-n.x;n.outY=p.y-n.y;n.inX=-n.outX;n.inY=-n.outY});return}if(op.kind==="point"){mutate(d=>{const n=d.nodes[op.i];if(!n)return;if(op.h==="anchor"){const dx=p.x-op.start.x,dy=p.y-op.start.y;n.x=op.node.x+dx;n.y=op.node.y+dy}else{const dx=p.x-n.x,dy=p.y-n.y;if(op.h==="in"){n.inX=dx;n.inY=dy;if(n.smooth){n.outX=-dx;n.outY=-dy}}else{n.outX=dx;n.outY=dy;if(n.smooth){n.inX=-dx;n.inY=-dy}}}})}}
  function up(){drag.current=null}
  function wheel(e){e.preventDefault();const p=screenToWorld(e),factor=e.deltaY<0?1.12:.89,next=Math.min(8,Math.max(.15,zoom*factor));const r=canvas.current.getBoundingClientRect();setPan({x:e.clientX-r.left-p.x*next,y:e.clientY-r.top-p.y*next});setZoom(next)}
  function setPaint(k,v){if(k==="fill")setFill(v);if(k==="stroke")setStroke(v);if(k==="strokeWidth")setStrokeWidth(Number(v)||0);setDoc(cur=>{const n=clone(cur),p=n.paths[0]||{id:uid("path"),d:dFromNodes(n.nodes,n.closed)};p[k]=k==="strokeWidth"?Number(v)||0:v;n.paths=[p,...n.paths.slice(1)];return n})}
  function save(){const a=assetWithPath({...doc,name:doc.name||"Vector",paths:[{...(doc.paths[0]||{}),fill,stroke,strokeWidth},...doc.paths.slice(1)]});onSave?.(a);setDoc(a)}
  function exportSvg(){const a=assetWithPath(doc),body=(a.paths||[]).map(p=>`<path d="${p.d}" fill="${p.fill||"none"}" stroke="${p.stroke||"none"}" stroke-width="${p.strokeWidth||0}" fill-rule="${p.fillRule||"nonzero"}"/>`).join("");const svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="${a.viewBox}">${body}</svg>`;const blob=new Blob([svg],{type:"image/svg+xml"}),link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download=(a.name||"vector")+".svg";link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000)}
  const active=doc.nodes[selected];
  return <div className="evw-backdrop"><div className="evw-shell"><header><div><b>VECTOR WORKSPACE</b><span>Path2D · DPR · Bézier nodes · handles · pan/zoom</span></div><div><button onClick={save}>Salvar</button><button onClick={()=>{save();onInsert?.(assetWithPath(doc))}}>Salvar + inserir</button><button onClick={exportSvg}>SVG</button><button onClick={onClose}>×</button></div></header><aside><h4>TOOLS</h4>{["pen","node","preview"].map(t=><button className={tool===t?"on":""} key={t} onClick={()=>setTool(t)}>{t}</button>)}<h4>DOCUMENT</h4><label>Nome<input value={doc.name} onChange={e=>setDoc(d=>({...d,name:e.target.value}))}/></label><div className="evw-grid2"><label>W<input type="number" value={doc.width} onChange={e=>setDoc(d=>({...d,width:Math.max(1,Number(e.target.value)||1)}))}/></label><label>H<input type="number" value={doc.height} onChange={e=>setDoc(d=>({...d,height:Math.max(1,Number(e.target.value)||1)}))}/></label></div><label className="evw-check"><input type="checkbox" checked={doc.closed} onChange={e=>setDoc(d=>assetWithPath({...d,closed:e.target.checked}))}/>Closed path</label><h4>PAINT</h4><label>Fill<input value={fill} onChange={e=>setPaint("fill",e.target.value)}/></label><label>Stroke<input value={stroke} onChange={e=>setPaint("stroke",e.target.value)}/></label><label>Stroke width<input type="number" value={strokeWidth} onChange={e=>setPaint("strokeWidth",e.target.value)}/></label>{active&&<><h4>NODE {selected+1}</h4><label className="evw-check"><input type="checkbox" checked={active.smooth} onChange={e=>mutate(d=>{d.nodes[selected].smooth=e.target.checked})}/>Smooth mirrored handles</label><button onClick={()=>{mutate(d=>d.nodes.splice(selected,1));setSelected(-1)}}>Excluir node</button></>}</aside><main><canvas ref={canvas} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up} onWheel={wheel}/><div className="evw-status">{Math.round(zoom*100)}% · {doc.nodes.length} nodes · Space+drag pan · Wheel zoom · Delete node</div></main></div><style jsx global>{`
  .evw-backdrop{position:fixed;z-index:100300;inset:0;background:rgba(2,8,23,.82);display:grid;place-items:center;padding:24px}.evw-shell{width:min(1480px,98vw);height:min(920px,94vh);display:grid;grid-template-columns:220px 1fr;grid-template-rows:54px 1fr;background:#0a1220;border:1px solid #334155;border-radius:14px;overflow:hidden;box-shadow:0 40px 120px rgba(0,0,0,.5)}.evw-shell>header{grid-column:1/-1;display:flex;justify-content:space-between;align-items:center;padding:0 14px;border-bottom:1px solid #28384e}.evw-shell>header b,.evw-shell>header span{display:block}.evw-shell>header b{font-size:11px;color:#fff;letter-spacing:.08em}.evw-shell>header span{font-size:7px;color:#8296aa;margin-top:3px}.evw-shell>header>div:last-child{display:flex;gap:6px}.evw-shell button{border:1px solid #3b4c62;background:#142238;color:#e2e8f0;border-radius:7px;padding:7px 9px;font-size:8px;font-weight:900;cursor:pointer}.evw-shell button.on{background:#6d28d9;border-color:#8b5cf6}.evw-shell>aside{grid-column:1;padding:12px;border-right:1px solid #28384e;overflow:auto}.evw-shell>aside h4{font-size:7px;letter-spacing:.13em;color:#a78bfa;margin:12px 0 7px}.evw-shell>aside>button{width:100%;margin-bottom:5px}.evw-shell label{display:block;font-size:7px;color:#9fb0c0;margin:7px 0}.evw-shell input{width:100%;margin-top:4px;border:1px solid #33465c;background:#101d2d;color:#e5eef6;border-radius:6px;padding:7px;font-size:8px}.evw-grid2{display:grid;grid-template-columns:1fr 1fr;gap:6px}.evw-check{display:flex!important;align-items:center;gap:7px}.evw-check input{width:auto;margin:0}.evw-shell>main{position:relative;min-width:0;min-height:0}.evw-shell canvas{display:block;width:100%;height:100%;touch-action:none;cursor:crosshair}.evw-status{position:absolute;left:10px;bottom:10px;padding:6px 9px;border-radius:7px;background:rgba(2,8,23,.8);color:#94a3b8;font:700 7px Arial;pointer-events:none}
  @media(max-width:800px){.evw-backdrop{padding:0}.evw-shell{width:100vw;height:100vh;border-radius:0;grid-template-columns:160px 1fr}}
  `}</style></div>
}
