import {Nav,Footer} from "./components";
import HomeDemo from "./components/HomeDemo";
import home from "../data/site/home.json";

const ecosystem=[
 ["01","Rota Inteligente","Planejamento adaptativo até a prova, com bibliografia, capítulos, calendário e reprogramação.","/plataforma"],
 ["02","Hoje + Insights","A plataforma transforma sua situação atual em uma próxima missão objetiva.","/plataforma"],
 ["03","11 mil+ questões","Banco validado, filtros, cadernos e prática conectada ao seu desempenho.","/produtos/banco-de-questoes"],
 ["04","Treino Inteligente","Questões selecionadas pelas suas fraquezas, revisões e momento da preparação.","/treino-adaptativo"],
 ["05","Centro de Revisão","Erros, tópicos frágeis e repetição espaçada reunidos em uma única fila.","/centro-de-revisao"],
 ["06","Simulados diagnósticos","O resultado deixa de ser apenas uma nota e se transforma em plano de recuperação.","/produtos/simulados"],
 ["07","RIPEAM 3D","Explore, identifique e resolva situações de manobra em um laboratório visual.","/flashcards/ripeam/3d"],
 ["08","Contramestre IA","Tutor contextual que pode considerar sua preparação e a bibliografia disponível.","/contramestre"],
 ["09","Flashcards + Mapas","Recuperação ativa e organização visual integradas à rotina de estudo.","/produtos/flashcards-mapas-mentais"],
 ["10","Busca Universal","Encontre ferramentas, tópicos e questões sem navegar por vários menus.","/pesquisar"],
 ["11","Trajetória + Prontidão","Acompanhe domínio, consistência, cobertura e evolução ao longo da preparação.","/minha-trajetoria"],
 ["12","Estudo offline","Continue parte da experiência mesmo com conectividade limitada e sincronize ao retornar.","/plataforma"]
];

export default function Home(){
 const features=home.knowledge.features;
 return <><Nav/><main>
  <section className="hero heroEstibordo homeHeroV3"><div className="heroChart"></div><div className="heroCompass"></div><div className="heroCopy"><div className="eyebrow">PRATICAGEM • PREPARAÇÃO PSCPP</div><h1>Prepare-se para chegar <span className="heroAccent">competitivo</span> ao processo seletivo.</h1><p>Da primeira descoberta sobre a Praticagem à preparação avançada para o PSCPP: plano de estudos, bibliografia, questões, simulados, revisão inteligente, IA e treinamento visual em um único sistema de aprendizagem.</p><div className="heroActions"><a className="btn primary" href="/cadastro">Quero começar minha preparação</a><a className="btn btnDark home-platform-cta" href="#diferenciais">Já conheço o PSCPP — ver ferramentas</a></div><div className="heroTrust"><span>✓ Preparação especializada</span><span>✓ Ferramentas conectadas</span><span>✓ Evolução mensurável</span></div></div><div className="heroVisual"><div className="hotelFlag"><span></span><span></span></div><img className="heroPortPhoto" src={home.hero.image.src} alt={home.hero.image.alt}/><div className="heroFloating"><small>ESTIBORDO LEARNING OS</small><strong>Seu estudo sabe o que precisa acontecer em seguida.</strong></div></div></section>

  <section className="pilotageIntro" id="praticagem"><div className="homeContainer pilotageGrid"><div><div className="eyebrow">NUNCA OUVIU FALAR EM PRATICAGEM?</div><h2>Existe um profissional especializado em assessorar a condução de grandes navios em águas restritas.</h2><p>O <strong>Prático</strong> atua com conhecimento local especializado para apoiar manobras e navegação em regiões onde características do porto, canal, tráfego, maré, vento e corrente exigem elevado domínio técnico.</p><p>Para quem deseja seguir esse caminho no Brasil, o <strong>PSCPP</strong> é o Processo Seletivo à Categoria de Praticante de Prático. A preparação envolve uma bibliografia extensa e conhecimento marítimo multidisciplinar.</p><div className="pilotageActions"><a className="btn primary" href="/sobre-a-praticagem">Entender a Praticagem em 2 minutos</a><a href="/sobre-a-praticagem/como-se-tornar-um-pratico">Como se tornar um Prático →</a></div></div><aside><span>DO ZERO AO PSCPP</span><ol><li><b>01</b><div><strong>Descubra a carreira</strong><small>Entenda Praticagem, atribuições e o processo.</small></div></li><li><b>02</b><div><strong>Conheça a seleção</strong><small>Veja o nível de preparação exigido.</small></div></li><li><b>03</b><div><strong>Construa sua rota</strong><small>Organize bibliografia, prática e revisões.</small></div></li><li><b>04</b><div><strong>Meça e ajuste</strong><small>Use desempenho para corrigir o rumo.</small></div></li></ol></aside></div></section>

  <section className="homeChallenge"><div className="homeContainer"><div className="sectionIntro"><div className="eyebrow">UMA PROVA DESSE NÍVEL EXIGE MAIS</div><h2>Não basta acumular PDFs e resolver questões aleatórias.</h2><p>O desafio é transformar bibliografia, prática, erros e tempo disponível em uma preparação coerente por meses.</p></div><div className="challengeGrid"><article><b>Bibliografia extensa</b><span>O que estudar e em qual ordem?</span></article><article><b>Conteúdo multidisciplinar</b><span>Como manter domínio em várias frentes?</span></article><article><b>Erros recorrentes</b><span>Quando e como voltar ao conteúdo?</span></article><article><b>Tempo limitado</b><span>Onde cada hora produz mais ganho?</span></article></div><div className="challengeAnswer"><span>FOI PARA ORGANIZAR ESSE PROBLEMA QUE CONSTRUÍMOS A ESTIBORDO.</span><strong>Não compare apenas quantidade de questões. Compare o que você consegue fazer com elas.</strong></div></div></section>

  <section className="homeDifferentials" id="diferenciais"><div className="homeContainer"><div className="sectionIntro"><div className="eyebrow">O DIFERENCIAL ESTÁ NA CONEXÃO</div><h2>Uma plataforma em que cada etapa alimenta a próxima.</h2><p>Questões, simulados e leituras não terminam quando você clica em concluir. Eles geram sinais que ajudam a orientar revisão, treino e planejamento.</p></div><div className="learningLoop"><span>ESTUDAR</span><i>→</i><span>MEDIR</span><i>→</i><span>DIAGNOSTICAR</span><i>→</i><span>REVISAR</span><i>→</i><span>REPLANEJAR</span></div><div className="differentialGrid"><article><em>01</em><h3>Seu estudo sabe o que fazer hoje.</h3><p>Rota Inteligente, Dashboard/Hoje e ESTIBORDO Insights convertem planejamento em ações concretas.</p><a href="/plataforma">Ver a Rota Inteligente →</a></article><article><em>02</em><h3>O erro não termina no gabarito.</h3><p>Fraquezas, Caderno de Erros, Centro de Revisão e Treino Inteligente fecham o ciclo de recuperação.</p><a href="/centro-de-revisao">Conhecer o Centro de Revisão →</a></article><article><em>03</em><h3>O simulado vira diagnóstico.</h3><p>Desempenho por matéria revela prioridades e orienta a próxima sessão, em vez de entregar apenas uma nota.</p><a href="/produtos/simulados">Ver os simulados →</a></article><article className="ripeamFeature"><em>04</em><div className="ripeamLights"><i/><i/><i/></div><h3>RIPEAM para compreender visualmente.</h3><p>Explore luzes, marcas e situações de encontro; identifique cenários e treine decisões em ambiente 3D.</p><a href="/flashcards/ripeam/3d">Conhecer o RIPEAM 3D →</a></article><article className="contramestreFeature"><em>05</em><span className="aiBadge">CONTRAMESTRE</span><h3>IA com contexto da sua preparação.</h3><p>Um tutor acadêmico que pode considerar seus sinais de estudo e trabalhar com a bibliografia disponível na plataforma.</p><a href="/contramestre">Conhecer o Contramestre →</a></article></div></div></section>

  <section className="homeDemo"><div className="homeContainer demoGrid"><div><div className="eyebrow">EXPERIMENTE A LÓGICA</div><h2>Uma resposta deve gerar mais do que “certo” ou “errado”.</h2><p>Responda à demonstração. Na experiência completa, respostas alimentam domínio por tópico, análise de fraquezas e próximos passos de revisão.</p></div><HomeDemo/></div></section>

  <section className="homeEcosystem"><div className="homeContainer"><div className="sectionIntro"><div className="eyebrow">TUDO A BORDO</div><h2>Do planejamento ao laboratório 3D.</h2><p>Um ecossistema construído especificamente em torno da preparação para o PSCPP.</p></div><div className="ecosystemGrid">{ecosystem.map(([n,title,text,href])=><a href={href} key={title}><span>{n}</span><strong>{title}</strong><p>{text}</p><b>Explorar →</b></a>)}</div></div></section>

  <section className="homeComparison"><div className="homeContainer"><div className="sectionIntro"><div className="eyebrow">PREPARAÇÃO CONECTADA</div><h2>O diferencial não é ter mais uma ferramenta. É todas trabalharem juntas.</h2></div><div className="comparisonTable"><div className="comparisonHead"><span>PREPARAÇÃO FRAGMENTADA</span><strong>ESTIBORDO</strong></div>{[["Cronograma estático","Rota que acompanha sua preparação"],["Questões isoladas","Questões conectadas ao diagnóstico"],["Nota do simulado","Diagnóstico + plano de recuperação"],["Lista de erros","Centro de Revisão e treino direcionado"],["RIPEAM por leitura","Laboratório RIPEAM 3D"],["Chat de IA genérico","Contramestre contextual"],["Você decide sozinho o que revisar","Prioridades orientadas por desempenho"],["Várias ferramentas separadas","Um único ecossistema de aprendizagem"]].map(([a,b])=><div className="comparisonRow" key={a}><span>{a}</span><b>→</b><strong>{b}</strong></div>)}</div></div></section>

  <section className="homeDark"><div className="homeContainer"><div className="sectionIntro"><div className="eyebrow">{home.knowledge.eyebrow}</div><h2>Estude as disciplinas. Treine para dominá-las.</h2><p>Conteúdo técnico, prática e revisão para transformar uma bibliografia extensa em conhecimento recuperável.</p></div><div className="featureGrid">{features.map(item=><article className="featureCard" key={item.title}><img src={"/estibordo/icones/"+item.icon+".svg"} alt=""/><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></div></section>

  <section className="homePersonas"><div className="homeContainer"><div className="sectionIntro"><div className="eyebrow">COMECE DO PONTO EM QUE VOCÊ ESTÁ</div><h2>A mesma plataforma. Três portas de entrada.</h2></div><div className="personaGrid"><article><span>ESTOU DESCOBRINDO</span><h3>Nunca estudei para o PSCPP.</h3><p>Entenda primeiro a Praticagem e depois construa sua rota de preparação.</p><a href="/sobre-a-praticagem">Quero conhecer a Praticagem →</a></article><article><span>JÁ ESTOU ESTUDANDO</span><h3>Conheço a prova e quero evoluir.</h3><p>Use diagnóstico, treino inteligente e revisão para tornar o estudo mais preciso.</p><a href="/cadastro">Quero evoluir meu estudo →</a></article><article><span>VENHO DO MAR</span><h3>Já tenho experiência marítima.</h3><p>Transforme conhecimento profissional em preparação estruturada para o processo seletivo.</p><a href="#diferenciais">Ver ferramentas avançadas →</a></article></div></div></section>

  <section className="dashboardPreview"><div className="homeContainer previewGrid"><div className="previewCopy"><div className="eyebrow">NÃO ESTUDE NO ESCURO</div><h2>Saiba onde está evoluindo — e onde ainda está perdendo pontos.</h2><p>Prontidão, domínio, cobertura, consistência, revisões e histórico transformados em direção para o próximo estudo.</p><a className="btn primary" href="/cadastro">Quero acompanhar minha evolução</a></div><div className="dashboardMock"><div className="mockTop"><img src="/estibordo/logos/estibordo-logo-final.png" alt="ESTIBORDO"/><span>MINHA ROTA</span></div><div className="mockBody"><div className="readiness"><div className="ring"><b>{home.dashboardPreview.readinessScore}</b><small>{home.dashboardPreview.readinessScale}</small></div><p>{home.dashboardPreview.readinessText}</p></div><div className="performance"><h4>{home.dashboardPreview.performanceTitle}</h4>{home.dashboardPreview.performance.map(({name,value})=><div className="perf" key={name}><span>{name}</span><i><b style={{width:value}}></b></i><strong>{value}</strong></div>)}</div></div></div></div></section>

  <section className="homeFinalCta"><div className="homeContainer"><div className="finalCtaBox"><span>SEU ESTUDO TEM UM DESTINO</span><h2>Coloque sua preparação no rumo certo.</h2><p>Da primeira descoberta sobre a Praticagem ao acompanhamento avançado para o PSCPP, a ESTIBORDO foi construída para acompanhar toda a jornada.</p><div><a className="btn primary" href="/cadastro">Começar minha preparação</a><a className="btn finalSecondary" href="/plataforma">Explorar a plataforma</a></div><small>Conheça a experiência antes de decidir como continuar.</small></div></div></section>
 </main><Footer/></>
}