"use client";
import {STANDALONE_STORES} from "./schema";import {standaloneAll,standaloneGet,standalonePut} from "./store";import {appendStandaloneChange} from "./journal";
function now(){return new Date().toISOString()}
export async function getLocalProfile(){return standaloneGet(STANDALONE_STORES.profile,"current")}
export async function saveLocalProfile(patch){const current=await getLocalProfile()||{id:"current"};const value={...current,...patch,id:"current",updated_at:now()};await standalonePut(STANDALONE_STORES.profile,value);await appendStandaloneChange("profile.update",patch,{id:"profile:"+value.updated_at});return value}
export async function getLocalPreferences(){return standaloneGet(STANDALONE_STORES.preferences,"current")}
export async function saveLocalPreferences(patch){const current=await getLocalPreferences()||{id:"current"};const value={...current,...patch,id:"current",updated_at:now()};await standalonePut(STANDALONE_STORES.preferences,value);await appendStandaloneChange("preferences.update",patch,{id:"preferences:"+value.updated_at});return value}
export async function saveLocalStudyTask(body){const id=body.kind==="bibliography"?`bibliography:${body.bibliography_key}:${body.section_key}`:`task:${body.plan_date}:${body.task_key}`;const value={id,...body,updated_at:now()};await standalonePut(body.kind==="bibliography"?STANDALONE_STORES.bibliography:STANDALONE_STORES.studyPlan,value);await appendStandaloneChange(body.kind==="bibliography"?"reading.progress":"study.task",body,{id});return value}
export async function saveLocalUnavailability(body){const id=`unavailability:${body.plan_date}`;const value={id,...body,updated_at:now()};await standalonePut(STANDALONE_STORES.studyPlan,value);await appendStandaloneChange("study.unavailability",body,{id});return value}
export async function startLocalStudySession(body){const id=globalThis.crypto?.randomUUID?.()||String(Date.now());const value={id,...body,started_at:now(),status:"active"};await standalonePut(STANDALONE_STORES.studySessions,value);await appendStandaloneChange("study.session.start",value,{id:"session-start:"+id});return value}
export async function stopLocalStudySession(id){const current=await standaloneGet(STANDALONE_STORES.studySessions,id);if(!current)return null;const value={...current,status:"stopped",stopped_at:now()};await standalonePut(STANDALONE_STORES.studySessions,value);await appendStandaloneChange("study.session.stop",{session_id:id,stopped_at:value.stopped_at},{id:"session-stop:"+id});return value}
export async function listLocalStudyPlan(){return standaloneAll(STANDALONE_STORES.studyPlan)}
