import {Nav,Footer} from "../components";import styles from "../legal.module.css";
export const metadata={title:"Termos de Uso e Contratação"};
export default function Page(){return <><Nav/><main className={styles.page}><article className={styles.wrap}>
<span className={styles.eyebrow}>ESTIBORDO • CONTRATO ELETRÔNICO</span><h1>Termos de Uso e Contratação</h1>
<p className={styles.updated}>Versão vigente: 08 de setembro de 2026.</p>
<p>Estes Termos regulam o acesso e a contratação da plataforma educacional ESTIBORDO. As normas de proteção do consumidor e de proteção de dados aplicáveis permanecem integralmente preservadas.</p>
<h2>1. Identificação do fornecedor</h2><p>A ESTIBORDO é operada pelo fornecedor identificado abaixo. Antes da abertura comercial definitiva, os campos entre colchetes deverão ser preenchidos com os dados cadastrais reais.</p>
<ul><li><strong>Fornecedor:</strong> [NOME COMPLETO OU RAZÃO SOCIAL]</li><li><strong>CPF/CNPJ:</strong> [PREENCHER]</li><li><strong>Endereço físico:</strong> [PREENCHER]</li><li><strong>Contato eletrônico:</strong> estibordopscpp@gmail.com</li></ul>
<h2>2. Objeto e natureza educacional</h2><p>A ESTIBORDO disponibiliza questões, simulados, planejamento, revisão, flashcards, mapas mentais, recursos tridimensionais, acompanhamento de desempenho e funcionalidades assistidas por inteligência artificial voltadas à preparação para o PSCPP.</p>
<p>A ESTIBORDO é iniciativa privada e independente. Não integra, representa ou mantém vínculo institucional com a Marinha do Brasil, Diretoria de Portos e Costas, Autoridade Marítima, banca examinadora ou órgão responsável pelo PSCPP. A plataforma não garante aprovação, classificação, convocação ou resultado profissional.</p>
<h2>3. Fontes oficiais</h2><p>Editais, Normas da Autoridade Marítima, publicações oficiais e comunicações dos órgãos competentes prevalecem em caso de divergência. O usuário deve conferir informações críticas e atualizações diretamente nas fontes oficiais.</p>
<h2>4. Cadastro, capacidade e segurança</h2><p>O usuário deve fornecer informações verdadeiras, completas e atualizadas, proteger suas credenciais e comunicar suspeitas de acesso indevido. A conta é pessoal e intransferível. A contratação por pessoa sem plena capacidade civil deverá observar a representação ou assistência legal aplicável.</p>
<h2>5. Licença de uso</h2><p>O acesso concede licença limitada, pessoal, revogável, não exclusiva e intransferível para utilização educacional durante o período contratado. Não há cessão de propriedade intelectual.</p>
<h2>6. Planos, preço e duração</h2><p>Preço total, prazo de acesso, forma de pagamento, parcelamento, disponibilidade e eventuais restrições são apresentados antes da conclusão da compra e integram a oferta. O plano anual atualmente ofertado concede 365 dias de acesso após a confirmação do pagamento, salvo oferta expressamente diferente.</p>
<h2>7. Pagamento</h2><p>O pagamento é processado por provedor externo. Dados de cartão e outros dados financeiros inseridos no ambiente do provedor não são armazenados diretamente pela ESTIBORDO. A liberação pode depender da confirmação do pagamento e de verificações legítimas de segurança e antifraude.</p>
<h2>8. Direito de arrependimento</h2><p>Nas contratações sujeitas ao Código de Defesa do Consumidor, o consumidor poderá exercer o direito de arrependimento no prazo legal de 7 (sete) dias, contado da assinatura ou do recebimento do serviço, conforme a legislação aplicável. O pedido poderá ser encaminhado pelo canal de atendimento indicado nestes Termos, sem prejuízo de mecanismo eletrônico específico disponibilizado pela plataforma.</p>
<h2>9. Cancelamento, reembolso, estorno e chargeback</h2><p>As regras operacionais constam da <a href="/cancelamento-e-reembolso">Política de Cancelamento, Arrependimento e Reembolso</a>. Nenhuma disposição será interpretada como renúncia a direito legal do consumidor. Estorno, reembolso integral ou chargeback confirmado poderá encerrar o acesso vinculado à respectiva compra.</p>
<h2>10. Renovação</h2><p>A ESTIBORDO não realizará renovação automática sem informação prévia clara e autorização válida. Se uma modalidade recorrente vier a ser oferecida, suas condições serão apresentadas antes da contratação.</p>
<h2>11. Propriedade intelectual</h2><p>São protegidos, na extensão permitida pela legislação, o software, identidade visual, organização e taxonomia proprietárias, bancos de questões autorais, explicações, simulados, flashcards, mapas, recursos e cenas 3D, textos, materiais didáticos e demais criações originais da ESTIBORDO.</p>
<h2>12. Usos proibidos</h2><p>É proibido realizar scraping ou extração automatizada não autorizizada, download em massa, reprodução sistemática, redistribuição, revenda, disponibilização pública, compartilhamento comercial de credenciais, contorno de controles de acesso ou utilização do conteúdo para formação de banco concorrente, ressalvados direitos assegurados por lei.</p>
<h2>13. Materiais de terceiros</h2><p>Marcas, obras, publicações e materiais de terceiros pertencem aos respectivos titulares. Referências bibliográficas não implicam cessão de direitos. A ESTIBORDO buscará utilizar conteúdo próprio, licenciado, autorizado ou permitido pela legislação.</p>
<h2>14. Conteúdo do usuário</h2><p>Anotações, mapas e materiais pessoais permanecem vinculados à conta. O usuário declara possuir autorização para o conteúdo que inserir e não deverá enviar material ilícito, violador de direitos de terceiros ou dados pessoais desnecessários.</p>
<h2>15. Inteligência artificial</h2><p>Recursos de IA podem produzir respostas imprecisas, incompletas ou desatualizadas e não substituem fontes oficiais. O usuário não deve inserir dados pessoais sensíveis ou informações confidenciais desnecessárias em campos destinados à IA.</p>
<h2>16. Disponibilidade e manutenção</h2><p>A plataforma poderá passar por manutenção, correções, evolução tecnológica e alterações de funcionalidades. A ESTIBORDO adotará esforços razoáveis de continuidade e segurança, sem prometer disponibilidade absoluta ou ininterrupta.</p>
<h2>17. Suspensão e encerramento</h2><p>Contas poderão ser suspensas ou encerradas em caso de fraude, abuso, violação relevante destes Termos, risco à segurança ou determinação legal, observados proporcionalidade, direitos do consumidor e possibilidade de esclarecimento quando cabível.</p>
<h2>18. Privacidade</h2><p>O tratamento de dados pessoais é descrito na <a href="/politica-de-privacidade">Política de Privacidade</a> e o uso de cookies e tecnologias equivalentes na <a href="/politica-de-cookies">Política de Cookies</a>.</p>
<h2>19. Alterações e versões</h2><p>Alterações relevantes serão identificadas por nova versão e, quando necessário, comunicadas ao usuário ou submetidas a novo aceite. A versão aceita pelo usuário será registrada para fins de auditoria e prova da relação contratual.</p>
<h2>20. Atendimento</h2><p>Solicitações contratuais, cancelamentos, reclamações e dúvidas podem ser encaminhadas para estibordopscpp@gmail.com. O atendimento eletrônico observará os prazos legais aplicáveis.</p>
<h2>21. Lei aplicável e solução de conflitos</h2><p>Aplica-se a legislação brasileira. Estes Termos não afastam foro, competência territorial ou mecanismos de proteção assegurados ao consumidor por norma cogente. As partes são incentivadas a buscar solução consensual antes da judicialização, sem impedir o acesso aos órgãos administrativos e ao Poder Judiciário.</p>
<div className={styles.links}><a href="/politica-de-privacidade">Privacidade</a><a href="/politica-de-cookies">Cookies</a><a href="/cancelamento-e-reembolso">Cancelamento e reembolso</a></div>
</article></main><Footer/></>;}