import {Nav,Footer} from "../components";import styles from "../legal.module.css";
export const metadata={title:"Termos de Uso e Contratação"};
export default function Page(){return <><Nav/><main className={styles.page}><article className={styles.wrap}>
<span className={styles.eyebrow}>ESTIBORDO • TERMOS DE USO</span><h1>Termos de Uso e Contratação</h1><p className={styles.updated}>Versão vigente: 08 de setembro de 2026.</p>
<p>Estes Termos regulam o acesso à ESTIBORDO, plataforma privada de estudos destinada a auxiliar a preparação para o PSCPP.</p>
<h2>1. Serviço oferecido</h2><p>A contratação concede ao usuário acesso, durante o período indicado na oferta, às ferramentas e conteúdos educacionais incluídos no plano adquirido, como questões, simulados, planejamento, revisão, recursos de estudo e funcionalidades digitais disponibilizadas pela plataforma.</p>
<h2>2. Plataforma independente e ausência de garantia de aprovação</h2><p>A ESTIBORDO é uma iniciativa privada e independente. Não integra, representa ou possui vínculo institucional com a Marinha do Brasil, Diretoria de Portos e Costas, Autoridade Marítima, banca examinadora ou órgão responsável pelo PSCPP. A plataforma é ferramenta de apoio aos estudos e não garante aprovação, classificação, convocação, desempenho mínimo ou qualquer resultado no processo seletivo.</p>
<p>Editais, normas e publicações oficiais prevalecem em caso de divergência. O usuário é responsável por acompanhar as fontes oficiais vigentes.</p>
<h2>3. Conta e acesso</h2><p>A conta é pessoal e intransferível. O usuário deve fornecer informações verdadeiras, manter suas credenciais protegidas e não compartilhar o acesso com terceiros. Poderão ser suspensas contas utilizadas de forma fraudulenta, compartilhadas abusivamente ou empregadas para contornar mecanismos de segurança, sem prejuízo dos direitos assegurados ao consumidor.</p>
<h2>4. Preço, pagamento e duração</h2><p>O preço, prazo de acesso, forma de pagamento e conteúdo do plano são informados antes da compra e integram a oferta. O acesso é liberado após a confirmação do pagamento. Não haverá renovação automática sem informação clara e autorização do usuário.</p>
<h2>5. Arrependimento, cancelamento e reembolso</h2><p>Nas hipóteses previstas pela legislação brasileira, o consumidor poderá exercer o direito de arrependimento dentro do prazo legal. O procedimento e demais regras estão descritos na <a href="/cancelamento-e-reembolso">Política de Cancelamento, Arrependimento e Reembolso</a>. Nenhuma disposição destes Termos limita direitos obrigatórios previstos no Código de Defesa do Consumidor.</p>
<h2>6. Conteúdo e propriedade intelectual</h2><p>O acesso à plataforma não transfere ao usuário direitos sobre software, identidade visual, questões autorais, explicações, simulados, materiais didáticos, recursos 3D e demais conteúdos próprios da ESTIBORDO. É proibida a reprodução sistemática, redistribuição, revenda, extração automatizada não autorizada, disponibilização pública ou utilização do conteúdo para criação de banco concorrente, ressalvados os usos permitidos por lei.</p>
<h2>7. Conteúdo de terceiros</h2><p>Marcas, obras e publicações de terceiros pertencem aos respectivos titulares. A indicação de bibliografia ou referência a publicação oficial não significa que a ESTIBORDO seja titular desses materiais.</p>
<h2>8. Recursos de inteligência artificial</h2><p>Recursos assistidos por inteligência artificial podem apresentar informações imprecisas, incompletas ou desatualizadas. Eles servem como apoio ao estudo e não substituem a bibliografia, os editais e as publicações oficiais.</p>
<h2>9. Disponibilidade</h2><p>A plataforma poderá passar por manutenção, correções e atualizações. Falhas temporárias de internet, infraestrutura ou serviços de terceiros podem afetar a disponibilidade. Isso não afasta os direitos do consumidor quando houver falha de prestação juridicamente relevante.</p>
<h2>10. Privacidade</h2><p>O tratamento de dados pessoais necessário ao funcionamento da plataforma é explicado na <a href="/politica-de-privacidade">Política de Privacidade</a>. Cookies e tecnologias necessárias à sessão são descritos na <a href="/politica-de-cookies">Política de Cookies</a>.</p>
<h2>11. Alterações</h2><p>Estes Termos poderão ser atualizados quando houver mudanças relevantes no serviço ou na legislação. Alterações que afetem de forma relevante a relação contratual serão comunicadas ou submetidas a novo aceite quando necessário.</p>
<h2>12. Atendimento e legislação</h2><p>Dúvidas, reclamações, cancelamentos e solicitações podem ser encaminhados para <strong>estibordopscpp@gmail.com</strong>. Aplica-se a legislação brasileira, preservados os direitos e competências assegurados ao consumidor.</p>
<div className={styles.links}><a href="/politica-de-privacidade">Privacidade</a><a href="/politica-de-cookies">Cookies</a><a href="/cancelamento-e-reembolso">Cancelamento e reembolso</a></div>
</article></main><Footer/></>;}