import {Nav,Footer} from "../components";import styles from "../legal.module.css";export const metadata={title:"Política de Cookies"};
export default function Page(){return <><Nav/><main className={styles.page}><article className={styles.wrap}>
<span className={styles.eyebrow}>PRIVACIDADE • COOKIES</span><h1>Política de Cookies</h1><p className={styles.updated}>Versão vigente: 08 de setembro de 2026.</p>
<p>A ESTIBORDO utiliza cookies e tecnologias equivalentes para viabilizar funcionalidades, segurança e, quando efetivamente implementados, recursos opcionais de preferência ou medição.</p>
<h2>1. O que são cookies</h2><p>Cookies são pequenos registros armazenados ou acessados pelo navegador. Tecnologias equivalentes, como armazenamento local, podem cumprir funções semelhantes.</p>
<h2>2. Cookies estritamente necessários</h2><p>O cookie <strong>pscpp_session</strong> é utilizado para manter a sessão autenticada. Ele é configurado como HttpOnly, utiliza Secure em produção, SameSite=Lax, caminho global e duração limitada pela configuração de sessão. Por ser necessário à autenticação e segurança, sua desativação pode impedir o uso de áreas privadas.</p>
<h2>3. Preferências</h2><p>Preferências locais poderão ser armazenadas para preservar escolhas do usuário. Quando não envolverem tratamento que dependa de consentimento, serão utilizadas apenas na extensão necessária à funcionalidade solicitada.</p>
<h2>4. Métricas e analytics</h2><p>Na versão auditada desta política, a aplicação principal não declara biblioteca dedicada de analytics ou publicidade no arquivo de dependências. Se ferramentas opcionais de analytics, publicidade, pixels ou rastreamento forem adicionadas, esta Política e o mecanismo de preferências deverão ser atualizados antes da ativação.</p>
<h2>5. Terceiros</h2><p>Ao interagir com checkout ou serviços externos, o respectivo fornecedor poderá utilizar cookies e tecnologias próprias sob sua responsabilidade e conforme seus documentos de privacidade. A ESTIBORDO limita integrações ao necessário para a prestação do serviço.</p>
<h2>6. Consentimento e preferências</h2><p>Cookies estritamente necessários não são condicionados a consentimento quando sua utilização decorrer de base legal adequada. Cookies opcionais baseados em consentimento deverão ficar desativados por padrão até manifestação positiva, com opção de rejeitar e de alterar a escolha posteriormente.</p>
<h2>7. Como controlar</h2><p>O usuário pode apagar ou bloquear cookies pelas configurações do navegador. O bloqueio de cookies essenciais pode impedir login e funcionamento de recursos privados. Quando a plataforma passar a utilizar categorias opcionais, disponibilizará mecanismo próprio para gerenciar essas preferências.</p>
<h2>8. Inventário</h2><ul><li><strong>pscpp_session</strong> — ESTIBORDO — autenticação e segurança — estritamente necessário — duração configurável, atualmente limitada no código a no máximo 90 dias.</li></ul>
<h2>9. Atualizações</h2><p>O inventário será revisto quando houver alteração de fornecedores, scripts, cookies ou tecnologias equivalentes.</p>
<div className={styles.links}><a href="/termos-de-uso">Termos</a><a href="/politica-de-privacidade">Privacidade</a></div>
</article></main><Footer/></>;}