"use client";
import {useEffect,useMemo,useState} from "react";
import styles from "./plano.module.css";
import {startTrackedStudySession,stopTrackedStudySession} from "../components/StudySessionTracker";
import {queueStudyTask} from "../../lib/offline-store";
import {standaloneEnabled} from "../../lib/standalone/runtime";
import {saveLocalStudyTask,saveLocalUnavailability} from "../../lib/standalone/services";

const dayNames=["DOM","SEG","TER","QUA","QUI","SEX","SÁB"];
function fmtDate(value){return new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"2-digit"}).format(new Date(value+"T12:00:00"))}
function todayIso(){return new Intl.DateTimeFormat("en-CA",{timeZone:"America/Sao_Paulo",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date())}
function radarPoints(subjects){const cx=120,cy=120,r=92,n=subjects.length;return subjects.map((s,i)=>{const a=(-Math.PI/2)+(i*2*Math.PI/n),v=Math.max(0,Math.min(100,Number(s.accuracy||0)))/100;return[cx+Math.cos(a)*r*v,cy+Math.sin(a)*r*v]})}
function polygon(points){return points.map(p=>p.join(",")).join(" ")}
function taskLabel(type){return type==="reading"?"LEITURA":type==="questions"?"QUESTÕES DE FIXAÇÃO":type==="review"?"REVISÃO":type==="simulado"?"SIMULADO PSCPP":String(type||"TAREFA").toUpperCase()}
function groupPublications(items){const map=new Map();for(const item of items){if(!map.has(item.bibliography_key))map.set(item.bibliography_key,{key:item.bibliography_key,publication:item.publication,source:item.source,items:[]});map.get(item.bibliography_key).items.push(item)}return[...map.values()]}

export default function PlanClient({plan}){
 const [week,setWeek]=useState(plan.week),[bibliography,setBibliography]=useState(plan.bibliography),[busy,setBusy]=useState(""),[message,setMessage]=useState(""),[taskMessages,setTaskMessages]=useState({}),[unavailableOpen,setUnavailableOpen]=useState("");
 const radar=useMemo(()=>radarPoints(plan.metrics.subjects),[plan.metrics.subjects]),today=todayIso();
 useEffect(()=>{if(plan.week?.snapshot_id||Number(plan.week?.offset||0)!==0)return;let cancelled=false;fetch("/api/study-plan/snapshot",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({week:Number(plan.week?.offset||0)})}).then(async r=>{if(r.ok||cancelled)return;const data=await r.json().catch(()=>({}));throw new Error(data.error||"Não foi possível preservar o planejamento desta semana.")}).catch(error=>{if(!cancelled)setMessage(error.message||"Não foi possível preservar o planejamento desta semana.")});return()=>{cancelled=true}},[plan.week?.offset,plan.week?.snapshot_id]);
 async function updateTask(day,task){if(task.status==="done")return;const planDate=task.source_plan_date||day.iso,key=day.iso+"|"+(task.display_key||task.key),completedAt=new Date().toISOString(),previousTask=task;setBusy(key);setMessage("");setTaskMessages(m=>({...m,[key]:"Salvando..."}));setWeek(w=>({...w,days:w.days.map(d=>({...d,tasks:d.tasks.map(t=>{const sameSource=(t.source_plan_date||d.iso)===planDate&&t.key===task.key,sameDisplay=d.iso===day.iso&&(t.display_key||t.key)===(task.display_key||task.key);return(sameSource||sameDisplay)?{...t,status:"done",completed_at:completedAt}:t})}))}));const body={kind:"task",plan_date:planDate,task_key:task.key,task_type:task.type,subject_slug:task.subject,status:"done",bibliography_key:task.bibliography_key||null,section_key:task.section_key||null,page_from:task.page_from||null,page_to:task.page_to||null,complete_bibliography_unit:task.type==="reading"&&!(task.page_from&&task.page_to),metadata:{title:task.title,description:task.description,href:task.href||null,target_questions:task.target_questions||null,fixation:task.fixation||null,bibliography_key:task.bibliography_key||null,section_key:task.section_key||null,reprogrammed:task.reprogrammed===true,displayed_plan_date:day.iso,source_plan_date:planDate,page_from:task.page_from||null,page_to:task.page_to||null}};try{if(standaloneEnabled()||!navigator.onLine){if(standaloneEnabled())await saveLocalStudyTask(body);else await queueStudyTask(body);await stopTrackedStudySession().catch(()=>{});setTaskMessages(m=>({...m,[key]:"✓ Salvo no dispositivo · sincronização pendente"}));return}const r=await fetch("/api/study-plan/task",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||"Não foi possível marcar a tarefa como feita.");const savedAt=data.item?.completed_at||completedAt;setWeek(w=>({...w,days:w.days.map(d=>({...d,tasks:d.tasks.filter(t=>!(t.reprogrammed&&(t.source_plan_date||d.iso)===planDate&&t.key===task.key)).map(t=>{const sameSource=(t.source_plan_date||d.iso)===planDate&&t.key===task.key,sameDisplay=d.iso===day.iso&&(t.display_key||t.key)===(task.display_key||task.key);return(sameSource||sameDisplay)?{...t,status:"done",completed_at:savedAt}:t})}))}));const bp=data.bibliography?.progress||data.progress||null;if(task.type==="reading"&&bp)setBibliography(items=>items.map(x=>x.bibliography_key===bp.bibliography_key&&x.section_key===bp.section_key?{...x,progress:bp}:x));await stopTrackedStudySession().catch(()=>{});setTaskMessages(m=>({...m,[key]:"✓ Tarefa concluída"}))}catch(error){setWeek(w=>({...w,days:w.days.map(d=>({...d,tasks:d.tasks.map(t=>d.iso===day.iso&&(t.display_key||t.key)===(task.display_key||task.key)?previousTask:t)}))}));setMessage(error.message||"Não foi possível marcar a tarefa como feita.")}finally{setBusy("")}}
 async function openTask(day,task){try{await startTrackedStudySession({task_key:task.key,subject_slug:task.subject||null,session_type:task.type||"study",plan_date:task.source_plan_date||day.iso,metadata:{title:task.title||null,reprogrammed:task.reprogrammed===true}})}catch{}window.location.assign(task.href||"/plano-de-estudos")}
 async function setUnavailable(day,reason,unavailable=true){const key="unavailable|"+day.iso;setBusy(key);try{if(standaloneEnabled()){await saveLocalUnavailability({plan_date:day.iso,unavailable,reason});setWeek(w=>({...w,days:w.days.map(d=>d.iso===day.iso?{...d,unavailable:unavailable?{reason:reason||"other",note:null}:null}:d)}));setUnavailableOpen("");return}const r=await fetch("/api/study-plan/unavailability",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({plan_date:day.iso,unavailable,reason})}),data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||"Não foi possível atualizar o dia.");setWeek(w=>({...w,days:w.days.map(d=>d.iso===day.iso?{...d,unavailable:unavailable?{reason:reason||"other",note:null}:null}:d)}));setUnavailableOpen("")}catch(error){setMessage(error.message)}finally{setBusy("")}}
 async function markBibliographyDone(item){if(item.progress?.status==="done")return;const key="bib|"+item.bibliography_key+"|"+item.section_key,body={kind:"bibliography",bibliography_key:item.bibliography_key,section_key:item.section_key,subject_slug:item.subject_slug,status:"done"};setBusy(key);try{if(standaloneEnabled()){await saveLocalStudyTask(body);setBibliography(list=>list.map(x=>x.bibliography_key===item.bibliography_key&&x.section_key===item.section_key?{...x,progress:{status:"done"}}:x));return}const r=await fetch("/api/study-plan/task",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||"Não foi possível atualizar a bibliografia.");setBibliography(list=>list.map(x=>x.bibliography_key===item.bibliography_key&&x.section_key===item.section_key?{...x,progress:data.progress||{status:"done"}}:x))}catch(error){setMessage(error.message)}finally{setBusy("")}}
 const plannedTasks=week.days.flatMap(d=>d.tasks).filter(t=>!t.reprogrammed),totalTasks=plannedTasks.length,doneTasks=plannedTasks.filter(t=>t.status==="done").length,weeklyPercent=totalTasks?Math.round(doneTasks/totalTasks*100):0,tracking=plan.tracking||{},backlogCount=Number(tracking.backlog_count||0),bibliographyTotal=bibliography.length,bibliographyDone=bibliography.filter(item=>item.progress?.status==="done").length,bibliographyPercent=bibliographyTotal?Math.round(bibliographyDone/bibliographyTotal*100):0;
 return <main className={styles.page}>
  <section className={styles.hero}><div><span>PLANO DE ESTUDOS INTELIGENTE</span><h1>Bibliografia completa antes da reta final</h1><p>Até 01/08/2027, o objetivo é concluir pelo menos uma leitura de 100% da bibliografia exigida. De 02/08 até a prova, o plano entra em revisão pesada: questões, simulados, erros e releitura seletiva.</p><a className={styles.downloadPlan} href="/api/study-plan/export">↓ Baixar Plano Completo (.txt)</a><a className={styles.downloadPlan} href="/api/study-plan/tutor-export">↓ Exportar Dossiê para Tutor IA (.txt)</a></div><div className={styles.heroStats}><div><strong>{plan.days_left}</strong><span>dias até a prova</span></div><div><strong>{plan.first_pass?.pending_sections??0}</strong><span>seções para 1ª leitura</span></div><div><strong>{plan.readiness}%</strong><span>índice de prontidão</span></div><div><strong>{bibliographyPercent}%</strong><span>bibliografia concluída</span></div></div></section>
  {message&&<div role="alert" className={styles.phaseBanner}><div><span>ATENÇÃO</span><strong>{message}</strong></div></div>}
  <section className={styles.trackingGrid}><article><span>ADERÊNCIA · 30 DIAS</span><strong>{tracking.adherence_percent??100}%</strong><small>{tracking.past_done||0} de {tracking.past_planned||0} metas concluídas</small></article><a href="/plano-de-estudos/pendencias"><span>PENDÊNCIAS</span><strong>{backlogCount}</strong><small>{tracking.backlog_minutes||0} min em aberto</small></a><article><span>CARGA DIÁRIA</span><strong>{tracking.daily_capacity_minutes||plan.onboarding?.daily_minutes||0} min</strong></article><article><span>TEMPO REAL · HOJE</span><strong>{tracking.study_time?.today_minutes||0} min</strong></article></section>
  <section className={styles.phaseBanner}><div><span>FASE ATUAL</span><strong>{plan.phase.label}</strong></div><div className={styles.phaseTrack}><i style={{width:Math.min(100,Math.max(5,100-(plan.days_left/430*100)))+"%"}}/></div><a href="/plano-de-estudos/configurar">Recalibrar questionário</a></section>
  <section className={styles.topGrid}><article className={styles.radarCard}><div className={styles.cardHead}><div><span>RADAR PSCPP</span><h2>Desempenho por matéria</h2></div><strong>{plan.readiness}%</strong></div><div className={styles.radarWrap}><svg viewBox="0 0 240 240">{[1,.75,.5,.25].map(scale=><polygon key={scale} points={polygon(plan.metrics.subjects.map((_,i)=>{const a=(-Math.PI/2)+(i*2*Math.PI/plan.metrics.subjects.length);return[120+Math.cos(a)*92*scale,120+Math.sin(a)*92*scale]}))} className={styles.radarGrid}/>)}<polygon points={polygon(radar)} className={styles.radarArea}/></svg><div className={styles.radarLegend}>{plan.metrics.subjects.map(s=><div key={s.slug}><span>{s.label}</span><b>{s.accuracy}%</b><small>{s.questions} respostas</small></div>)}</div></div></article><article className={styles.priorityCard}><div className={styles.cardHead}><div><span>ADAPTAÇÃO</span><h2>Prioridades atuais</h2></div></div><div className={styles.priorityList}>{plan.weighted_subjects.map((s,i)=><div key={s.slug}><b>{i+1}</b><div><strong>{s.label}</strong><span>{s.questions} respondidas · {s.errors} erros</span></div><em>{s.accuracy}%</em></div>)}</div><a className={styles.primaryAction} href="/treino-adaptativo">Começar Treino Adaptativo →</a></article></section>
  <section className={styles.calendar}><div className={styles.sectionHead}><div><span>PLANEJAMENTO SEMANAL · LEITURA → FIXAÇÃO → REVISÃO · DOMINGO + SIMULADO PSCPP</span><h2>{fmtDate(week.start)} a {fmtDate(week.end)}</h2><p>{doneTasks} de {totalTasks} tarefas concluídas · {weeklyPercent}%</p></div><div className={styles.weekNav}><a href={"/plano-de-estudos?semana="+(week.offset-1)}>← Semana anterior</a>{week.offset!==0&&<a href="/plano-de-estudos">Semana atual</a>}<a href={"/plano-de-estudos?semana="+(week.offset+1)}>Próxima semana →</a></div></div><div className={styles.weekProgress}><i style={{width:weeklyPercent+"%"}}/></div><div className={styles.daysGrid}>{week.days.map(day=><article className={day.active?styles.day:styles.dayOff} key={day.iso}><header><span>{dayNames[new Date(day.iso+"T12:00:00").getDay()]}</span><strong>{fmtDate(day.iso)}</strong></header>{!day.active?<p>Dia sem estudo programado.</p>:day.tasks.map(task=>{const key=day.iso+"|"+(task.display_key||task.key);const isDelayed=task.status!=="done"&&(task.reprogrammed===true||Boolean(task.source_plan_date&&task.source_plan_date!==day.iso));return <div className={task.status==="done"?styles.taskDone:isDelayed?styles.taskDelayed:styles.task} key={task.display_key||task.key}>{isDelayed&&<div className={styles.delayedBadge}>⚠ REPROGRAMADA · ATRASADA</div>}<div className={styles.taskMeta}><span>{taskLabel(task.type)}</span><em>{task.estimate_minutes||0} min</em></div><strong>{task.title}</strong><p>{task.description}</p><div className={styles.taskActions}><button onClick={()=>openTask(day,task)}>Abrir →</button><button disabled={busy===key||task.status==="done"} onClick={()=>updateTask(day,task)}>{task.status==="done"?"✓ Concluída":"Marcar concluída"}</button></div>{taskMessages[key]&&<small>{taskMessages[key]}</small>}</div>})}</article>)}</div></section>
  <section className={styles.bibliographySection}><div className={styles.sectionHead}><div><span>BIBLIOGRAFIA INTEGRADA</span><h2>Leituras, capítulos e páginas</h2><p>O mesmo catálogo alimenta o calendário e o arquivo TXT exportado.</p></div><div className={styles.bibProgress}>{bibliographyDone}/{bibliographyTotal}</div></div><div className={styles.bibliographyGrid}>{Object.entries(bibliography.reduce((a,x)=>{(a[x.subject_slug]||=[]).push(x);return a},{})).map(([subject,items])=><article key={subject}><h3>{plan.metrics.subjects.find(s=>s.slug===subject)?.label||subject}</h3><div className={styles.publicationList}>{groupPublications(items).map(pub=><div className={styles.publication} key={pub.key}><div className={styles.publicationHead}><strong>{pub.publication}</strong><small>{pub.source}</small></div>{pub.items.map(item=><div className={item.progress?.status==="done"?styles.readDone:styles.readItem} key={item.bibliography_key+"|"+item.section_key}><div><strong>{item.chapter||item.section}</strong><span>{item.page_start&&item.page_end?`páginas ${item.page_start}–${item.page_end}`:"Paginação não cadastrada"}</span></div><button disabled={item.progress?.status==="done"} onClick={()=>markBibliographyDone(item)}>{item.progress?.status==="done"?"✓ Done":"Done"}</button></div>)}</div>)}</div></article>)}</div></section>
 </main>;
}
