'use client';
import {useEffect} from 'react';
import baseDesign from '../../data/site/editor-design.json';

function safeUrl(value){const v=String(value||'').trim();return /^(javascript|vbscript|data:text\/html)/i.test(v)?'':v}
function bindAdvanced(record){if(!record||typeof record!=='object')return;for(const [selector,cfg] of Object.entries(record)){let nodes=[];try{nodes=[...document.querySelectorAll(selector)]}catch{continue}for(const node of nodes){if(!node||node.dataset.estibordoProBound==='1')continue;node.dataset.estibordoProBound='1';
    if(cfg.hoverBackground){node.addEventListener('mouseenter',()=>{node.dataset.estibordoProBg=node.style.backgroundColor||'';node.style.backgroundColor=cfg.hoverBackground});node.addEventListener('mouseleave',()=>{node.style.backgroundColor=node.dataset.estibordoProBg||''})}
    if(cfg.focusOutline){if(node.tabIndex<0)node.tabIndex=0;node.addEventListener('focus',()=>node.style.outline=cfg.focusOutline);node.addEventListener('blur',()=>node.style.outline='')}
    if(cfg.pressedScale){node.addEventListener('pointerdown',()=>{node.dataset.estibordoProTransform=node.style.transform||'';node.style.transform=(node.dataset.estibordoProTransform||'')+` scale(${cfg.pressedScale})`});const release=()=>node.style.transform=node.dataset.estibordoProTransform||'';node.addEventListener('pointerup',release);node.addEventListener('pointercancel',release);node.addEventListener('pointerleave',release)}
    if(cfg.prototypeAction&&cfg.prototypeAction!=='none'){node.style.cursor='pointer';node.addEventListener('click',e=>{const t=String(cfg.prototypeTarget||'');if(cfg.prototypeAction==='navigate'&&t){location.href=safeUrl(t)||'#';return}if(cfg.prototypeAction==='scroll-to'&&t){try{document.querySelector(t)?.scrollIntoView({behavior:'smooth',block:'center'})}catch{}return}if(cfg.prototypeAction==='open-modal'&&t){let m=null;try{m=document.querySelector(`[data-estibordo-modal="${CSS.escape(t)}"],#${CSS.escape(t)},${t}`)}catch{}if(m){m.hidden=false;m.setAttribute('aria-hidden','false')}return}if(cfg.prototypeAction==='close-modal'){const m=node.closest('[data-estibordo-modal],[role="dialog"]');if(m){m.hidden=true;m.setAttribute('aria-hidden','true')}}})}
  }}
}
function applyAdvanced(design){const routeKey=document.querySelector('[data-estibordo-not-found]')?'/__404':location.pathname;bindAdvanced(design?.global?.elements||{});bindAdvanced(design?.pages?.[routeKey]?.elements||{});const ds=design?.global?.designSystem||{};if(ds.variables&&typeof ds.variables==='object'){for(const [k,v] of Object.entries(ds.variables))document.documentElement.style.setProperty('--'+String(k).replace(/^--/,''),String(v))}}
export default function SiteDesignProRuntime(){useEffect(()=>{let active=baseDesign;const run=()=>{if(location.pathname.startsWith('/admin/editor'))return;applyAdvanced(active)};const msg=e=>{if(e.origin!==location.origin||e.data?.type!=='estibordo-editor-design'||!e.data?.design)return;active=e.data.design;run()};window.addEventListener('message',msg);run();const mo=new MutationObserver(()=>{clearTimeout(window.__estibordoProRuntimeTimer);window.__estibordoProRuntimeTimer=setTimeout(run,120)});mo.observe(document.body,{subtree:true,childList:true});return()=>{window.removeEventListener('message',msg);mo.disconnect()}},[]);return null}
